### ISSUE TITLE
Update unit tests to look at objects, not info statements

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#100]
Took a first cut at the furnace measure. To be reviewed by Scott. Then update the remaining hvac equipment measure unit tests.

**Comment by joseph-robertson** [comment]
- [x] Furnace
- [x] Central Air Conditioner
- [ ] Air Source Heat Pump
- [ ] Boiler
- [ ] Electric Baseboard
- [ ] Mini-Split Heat Pump
- [ ] Room Air Conditioner

**Comment by joseph-robertson** [comment]
- [ ] tests.rb

**Comment by shorowit** [comment]
There are non-HVAC measures that should also be updated to look at model objects. For example:
- [ ] Location
