### ISSUE TITLE
Multifamily modeling

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#101]
Remaining items to complete initial multifamily building implementation:
- [x] Complete implementation of OpenStudio BuildingUnit object - @nmerket 
  - [x] Hook up measures to new BuildingUnit object - @shorowit @joseph-robertson
  - [x] Update standardsNumberOfLivingUnits in SFA/MF geometry measures - @shorowit
- [x] Update HW distribution measure - @shorowit
- [x] Update SFA geometry measure code to accommodate rear units with Zone Multipliers - @joseph-robertson 
- [ ] Resolve energy discrepancies due to zone multipliers - @craigch99 @shorowit
  - [ ] Foundation perimeter calculation - STATUS: works for SL, FB, CS; not yet for UB
  - [ ] Specification for attached walls - adiabatic? or surface outside boundary condition?
  - [ ] Handling of foundation zones
  - [x] Lighting (exterior?)
  - [x] Airflow
  - [ ] Water heating
  - [x] Number of occupants
  - [ ] Add unit tests for above fixes
- [x] Allow Zone & Floor Multipliers input for MF geometry measure - @joseph-robertson 
  - [x] Zone Multipliers
  - [x] Floor Multipliers
- [ ] Compare results to BEopt-MF - @shorowit
- [x] Allow only one unit to be modeled - @joseph-robertson
  - [x] SFA geometry measure
  - [x] MF geometry measure
- [x] Use standardsNumberOfAboveGroundStories (finished stories) - @joseph-robertson
  - [x] Update SFD, SFA, MF geometry measures
  - [x] Update airflow measure (and remove get_building_stories method from geometry.rb)
- [x] Attics for SFA geometries - @joseph-robertson
- [ ] Figure out how to deal with assigning different beds/baths and occupancy values to (specific) units 
- [ ] Investigate reusing schedule objects, particularly in hot water measures
- [ ] HVAC sizing
- [ ] Think about central HVAC/WH system implementation
- @joseph-robertson @shorowit 

Long-term todo:
- Garages for SFA geometries
- Parking garages for MF geometries
- Other space types (common rooms, elevators, etc.)
- Allow F/B corridor orientation
- Single unit modeling (downside may be central system modeling)
- etc.

**Comment by joseph-robertson** [comment]
Do we know in what iteration the new BuildingUnit object will be available?

**Comment by shorowit** [comment]
TBD. Noel's still working on it, then will likely be reviewed by the OS team before merge, etc.
