### ISSUE TITLE
no energy use during shoulder season

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#102]
What's up with May and Oct:

![image](https://cloud.githubusercontent.com/assets/8516790/19006494/f995fc10-871c-11e6-86a9-22bb7f1052dc.png)

4 units, 2 stories, finished basement, zone multipliers:
![image](https://cloud.githubusercontent.com/assets/8516790/19006517/17c66d78-871d-11e6-9f03-0d8e3980627b.png)

Related to #77.

[out.zip](https://github.com/NREL/OpenStudio-BEopt/files/503790/out.zip)

**Comment by shorowit** [comment]
Hmm, maybe [my change to schedules.rb](https://github.com/NREL/OpenStudio-BEopt/commit/0794731dcefd40d856b81e8ac334c13a3a30fe0c#diff-0ecebfc9da1fb63cc8a5a32323b67ae3) broke it? 

@joseph-robertson Can you try backing out my change to see if it fixes things?

**Comment by joseph-robertson** [comment]
I tried running it with the version of schedules.rb before 0794731dcefd40d856b81e8ac334c13a3a30fe0c:

![image](https://cloud.githubusercontent.com/assets/8516790/19042662/19ee373c-894a-11e6-85e5-374d52b1dad7.png)
