### ISSUE TITLE
Split up/aggregate measures

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#106]
- [x] Split up measures by # speeds (1, 2, or variable) (higher priority):
  - [x] AC
  - [x] ASHP
- [x] Split up measures by electric vs fuel:
  - [x] Furnace
  - [x] Boiler 
- [x] Aggregate Water Heater gas/oil/propane measures into fuel measure
- [x] Aggregate appliance gas/propane measures into fuel measure

cc @joseph-robertson

**Comment by joseph-robertson** [comment]
I think this makes sense. For AC/ASHP we could then eliminate the Num Speeds input. Could we then use:
* CoilCoolingDXSingleSpeed for speed=1
* CoilCoolingDXMultiSpeed for speed=2
* CoilCoolingDXVariableSpeed for speed=4

?

**Comment by shorowit** [comment]
That's a question for @jonwinkler as to whether we are ready to switch to the variable speed model, but I'm guessing we're not yet ready. We probably have to keep using the CoilCoolingDXMultiSpeed object for our AC/ASHP variable speed units for now.

cc @jmaguire1 @ejhw

**Comment by jonwinkler** [comment]
I haven't tested the variable speed coil in quite some time. It's probably time to give it another shot but aren't we using it in Open Studio when we have a two-stage air conditioner and a furnace?

**Comment by shorowit** [comment]
We are using a multi-speed coil in that situation.

**Comment by shorowit** [comment]
Done.
