### ISSUE TITLE
HSPF calc - Check assumption of 10F cut-out temp

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BEopt#108]
I noticed that our HSPF calculation method assumes a compressor cut-out temperature of 10F (https://github.com/NREL/OpenStudio-BEopt/blob/77cffa1fd6c57f3e6b2b4497f4939822a888c98f/measures/ResidentialHVACMiniSplitHeatPump/measure.rb#L860). This may not be appropriate for mini-splits and variable-speed central heat pumps. It looks like we may have used the user input minimum temperature in the past, but it was commented out and hardcoded to 10F. We also use the value of 10F for single speed and 2-speed heat pumps.

Jon and I looked at the AHRI Standard (p 103, http://www.ahrinet.org/App_Content/ahri/files/standards%20pdfs/ANSI%20standards%20pdfs/ANSI.AHRI%20Standard%20210.240%20with%20Addenda%201%20and%202.pdf) which does not mention a value of 10F and suggests that the value can be a user input: "If no such temperature 
exists, Tj is always greater than Toff and Ton". We weren't able to track down where the value of 10F comes from; it could be from spreadsheets from Nordyne.

Jon and I agreed to not change the value for now, but we may want to revisit at a later date. The effect of lowering or eliminating this value is that our heat pump models would perform _worse_ for a given HSPF.

cc @jonwinkler @shorowit @joseph-robertson

**Comment by shorowit** [comment]
For what it's worth, it was changed from user input to 10F here:
https://cbr2.nrel.gov/BEopt2/trac/changeset/3668

(If you can't access it, go [here](https://cbr2.nrel.gov/BEopt2/trac/report/2), login, and then retry the URL.)
