### ISSUE TITLE
E+ HVAC autosizing

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#109]
Need to make some adjustments:
- [ ] Update Winter/Summer design days for all schedules based on Manual J approach. ([Zone Report measure](https://bcl.nrel.gov/node/82313) includes "disaggregation of the contributions of envelope and internal gains to the HVAC loads.")
- [ ] Update Sizing:Zone and Sizing:System objects as appropriate.
- [ ] Perform separate sizing run? See Standards project.
- [ ] Double-check results for various systems (e.g., ASHP heating/cooling/supplemental values).
- [ ] Validate results relative to BEopt/Manual J.

cc @jonwinkler @jmaguire1

**Comment by jonwinkler** [comment]
Another comparison between BEopt and OS should be run after completing the following modifications. I included the highest priority item from Scott's list above and added a few.

- [ ] Update winter/summer design days for all internal schedules based on Manual J approach (Internal gains should be 0 for winter design load calculation)
- [ ] Include winter/summer thermostat schedules based on setpoints used by Manual J approach (75°F for cooling, 68°F for heating)
- [ ] Update Sizing:Zone and Sizing:System 'Central Cooling Design Supply Air Temperature' to 13.33°C
- [ ] Update Sizing:Zone and Sizing:System 'Central Heating Design Supply Air Temperature' to 48.86°C (for now - this will likely need to be changed based on the heating system type)
- [ ] Update Sizing:System 'Design Outdoor Air Flow Rate' to 0 m3/s 
- [ ] Update Sizing:System '100% Outdoor Air in Cooling (and Heating)' to 'No'

cc @shorowit @jmaguire1

**Comment by shorowit** [comment]
Deferring work on this in lieu of https://github.com/NREL/OpenStudio-BEopt/issues/8.
