### ISSUE TITLE
Use EMPD model

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#110]
- [x] Needs to be wrapped in OS first
- [x] Pull request made in OpenStudio
- [x] Functional units tests complete in OpenStudio-resources
- [x] Will need to get appropriate inputs from Jason
- [x] Implement in residential measure(s)

**Comment by joseph-robertson** [comment]
https://github.com/NREL/OpenStudio/pull/2828

**Comment by joseph-robertson** [comment]
https://github.com/NREL/OpenStudio-resources/pull/17

**Comment by joseph-robertson** [comment]
[EMPD_idf.txt](https://github.com/NREL/OpenStudio-BEopt/files/1612101/EMPD_idf.txt)
[EMPD_idf_defaults.txt](https://github.com/NREL/OpenStudio-BEopt/files/1612103/EMPD_idf_defaults.txt)
[idfSnippet_EMPD_Furniture.txt](https://github.com/NREL/OpenStudio-BEopt/files/1612104/idfSnippet_EMPD_Furniture.txt)

**Comment by joseph-robertson** [comment]
The table below shows the surface area multipliers we used in our most recent residential simulations for the drywall, wood, and carpet. So if you have a 200 m^2 floor area, the surface area of the drywall would be 200*2.92 = 584 m^2. For wood, 200*0.31 = 62 m^2, etc. These are added in the internal mass object.

We also included the effects of furniture, see attached “…_Funriture.txt” for default setting values. The surface-area multiplier for furniture was 0.25. (200*0.25 = 50 m^2 for 200 m^2 floor area home).


  | Drywall | Wood | Carpet
-- | -- | -- | --
Generalized floor-area   multiplier | 2.92 | 0.31 | 0.64

**Comment by joseph-robertson** [comment]
Even when reducing solar absorptance to near zero, tests are showing heating/cooling discrepancies larger than expected. Up to 5.0 GJ difference in heating and 0.5 GJ difference in cooling. Going to defer further work on this for the time being.
