### ISSUE TITLE
ResidentialAirflow error

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#112]
Appears to be caused when a building has no heating and/or cooling HVAC system. Can you add a unit test and fix? I never saw this error with the ResidentialAirflowOriginalModel measure, so it seems specific to the new ResidentialAirflow measure.

```
[14:11:14.690864 ERROR] Measure Failed with Error: /mnt/openstudio/analysis_61d8fb2c-e625-4480-b8d2-5141334e2568/lib/resources/measures/ResidentialAirflow/measure.rb:2276:in `get'
/mnt/openstudio/analysis_61d8fb2c-e625-4480-b8d2-5141334e2568/lib/resources/measures/ResidentialAirflow/measure.rb:2276:in `_processNaturalVentilation'
/mnt/openstudio/analysis_61d8fb2c-e625-4480-b8d2-5141334e2568/lib/resources/measures/ResidentialAirflow/measure.rb:881:in `block in run'
/mnt/openstudio/analysis_61d8fb2c-e625-4480-b8d2-5141334e2568/lib/resources/measures/ResidentialAirflow/measure.rb:833:in `each'
/mnt/openstudio/analysis_61d8fb2c-e625-4480-b8d2-5141334e2568/lib/resources/measures/ResidentialAirflow/measure.rb:833:in `run'
```

**Comment by shorowit** [comment]
Here were the full set of measures that were run: [run.txt](https://github.com/NREL/OpenStudio-BEopt/files/569275/run.txt)

**Comment by joseph-robertson** [comment]
This happened because buildings with no HVAC system have no thermostat. I now check for thermostat before trying to pull the heating and cooling weekday and weekend setpoints. This also lead to noticing a bug involving the natural ventilation schedules. @shorowit Can this issue be closed now?
