### ISSUE TITLE
Revisit space types

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#117]
Current logic for determining types of spaces is somewhat complex and may not adequately cover every situation. It is sometimes also hard to differentiate between similar types of spaces.

Possible residential space types we'd initially support:
- Living
- Attic
- Garage
- Basement
- Crawlspace
- Pier & Beam?
- Corridor

If needed, we could eventually allow more granularity (bedroom, kitchen, bathroom, etc.).

Finished vs unfinished status will ultimately be handled separately via [Standards info.](https://github.com/NREL/OpenStudio-BEopt/issues/29)

**Comment by joseph-robertson** [comment]
TODOs:
- [ ] Create residential floorplan json file using the openstudio geometry editor
- [ ] Modify floorplan import measure to attach space types, thermal zones, building units
- [ ] Create default value for modified floorplan import measure
- [ ] Write unit tests for modified floorplan import measure
- [ ] Replace SFD geometry measure with modified floorplan measure in measure-info.json
- [ ] Run update_measures rake task to produce osw containing modified floorplan measure
- [ ] Run CLI with osw as argument to test and update residential measures
- [ ] Continue to update residential measures by producing different floorplan json files

**Comment by joseph-robertson** [comment]
![image](https://user-images.githubusercontent.com/8516790/28683607-68ffe5ec-72be-11e7-8e29-4498a9928953.png)

@shorowit, this seems like a geometry-editor bug. Not sure why adjacent surfaces between my living and garage spaces aren't "touching". See above image where the back wall of the garage does not match up with a living space wall.

[floorplan.json.txt](https://github.com/NREL/OpenStudio-BEopt/files/1180740/floorplan.json.txt)

**Comment by shorowit** [comment]
If you zoom in enough, you can see a gap in the floorplan in the geometry editor itself. The editor has some known issues related to snapping when drawing.

**Comment by shorowit** [comment]
Probably the same issue as this: https://github.com/NREL/openstudio-geometry-editor/issues/72

**Comment by joseph-robertson** [comment]
Notes from Slack:

copy Dan's floorplan import measure into OpenStudio-BEopt repo and add custom code:
- [ ] error-check if mix of spaces assigned/unassigned to zones
  - currently Dan's code does not assign thermal zones to spaces. therefore this is never an issue.
- [ ] if all spaces unassigned to zones, create zones based on spacetypes
- [ ] if all spaces assigned to zones, error-check if mix of finished/unfinished spaces in any zone
- [ ] error-check if unexpected spacetype name
- [ ] unit tests
