### ISSUE TITLE
Dehumidifier

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#119]
- [x] Difference between 'standalone' and 'ducted'? No; Jon says only used for costing.
- [x] Wait for sizing.rb to be complete before can use autosized water removal rate?
- [x] The finished basement (or other foundation type) doesn't get a zone hvac dehumidifier dx object

**Comment by joseph-robertson** [comment]
- [ ] Difference between 'standalone' and 'ducted'?
- [ ] Wait for sizing.rb to be complete before can use autosized water removal rate?

**Comment by shorowit** [comment]
@jonwinkler I don't find any difference in code between standalone/ducted dehumidifiers. Can you remind us about this?

**Comment by jonwinkler** [comment]
From EnergyPlus's perspective, they're the same. I think we only used the flag for costing.

**Comment by joseph-robertson** [comment]
I couldn't even get PSD's measure to run successfully. It looks to be heavily stubbed. I copied/pasted what code was useful, but there isn't much.

**Comment by jmaguire1** [comment]
Is the finished basement not getting a dehumidifer when you specify that the home has one something that was intended? I could see this definitely being something that would change based on specifying "standalone" vs "ducted", with you picking a zone (or all conditioned zones) for the standalone and the dehumidifier being in the HVAC loop when it's ducted. It looks like right now we specify the dehumidifier as ZoneHVAC equipment (so it's never on the air loop), so maybe the second case isn't possible in EnergyPlus? @jonwinkler, do you know why the dehumidifier is modeled this way now? I'm guessing it wouldn't be trivial to add the dehumidifer to the HVAC loop.

**Comment by jonwinkler** [comment]
@jmaguire1,
Perhaps the finished basement should be getting a dehumidifier when one is present in the living zone but the dehumidifier (both standalone and ducted options) were always intended to be whole-house dehumidifiers. Basements are less common in areas of the country where whole-house dehumidification is needed. Also don't forget that the latent loads in basements are quite small given how we presently  model them. Infiltration is zero (I think) and we don't account for latent loads to the soil moisture content. See the above comment - I think ducted and standalone dehumidifiers are identical except for costing; maybe there's an efficiency difference if Auto-calculated is used. Probably worth verifying.

**Comment by shorowit** [comment]
OK, so let's not include a dehumidifier in the finished basement for the time being.
