### ISSUE TITLE
Geometry flexibility

### ISSUE THREAD

**Issue by gjko** [NREL/OpenStudio-BEopt#131]
Is it possible to use geometry created by the user (possibly on SketchUp)?

**Comment by shorowit** [comment]
Technically it is possible if really desired, but there are a lot of ways that the geometry could be incompatible with the current set of measures (e.g., unknown spaces/zones, non-orthogonal walls, etc). Eventually we will get to the point of being able to handle most any residential building geometry someone creates, but this will take time.

**Comment by gjko** [comment]
And at the moment is it possible to create the geometry and then modify it on Sketchup?

For example, enlarging a little bit one side or modifying the windows.

I'm creating a draft model of an existing house with your workflow to compare it with the model I've already done. And possibly to use some of the measures (mini-split).
