### ISSUE TITLE
Aspect ratio (FB/LR)

### ISSUE THREAD

**Issue by gjko** [NREL/OpenStudio-BEopt#132]
Is it possible to give aspect ratio <1?
If I put a 0.7 value it gives the following error.
![err_geometry_sfd](https://cloud.githubusercontent.com/assets/14098958/23800809/5deea886-0573-11e7-8329-3673ead1d909.JPG)

```
in.rb:439:in `<main>': Error encountered. See result.ossr. (RuntimeError)


Script executing from: C:/Users/X/AppData/Local/Temp/OpenStudio.D12436/ApplyMeasureNow/UserScript
Found argument 'total_ffa' with value '696'.
Found argument 'living_height' with value '10'.
Found argument 'num_floors' with value '1'.
Found argument 'aspect_ratio' with value '0.7'.
Found argument 'garage_width' with value '4'.
Found argument 'garage_depth' with value '6'.
Found argument 'garage_protrusion' with value '1'.
Found argument 'garage_pos' with value 'Right'.
Found argument 'foundation_type' with value 'slab'.
Found argument 'foundation_height' with value '0'.
Found argument 'attic_type' with value 'finished attic'.
Found argument 'roof_type' with value 'flat'.
Found argument 'roof_pitch' with value '6:12'.
Found UserScript 'Create Residential Single-Family Detached Geometry'.
result = false
Processed 1 base script and 0 merged scripts
```

**Comment by joseph-robertson** [comment]
Yes, you can have an aspect ratio <1, but not with a protruding garage. An aspect ratio <1 causes the house attic ridge to run from front to back, and the measure currently does not handle protruding garages with this configuration.

**Comment by gjko** [comment]
Thank you, but I set a flat roof, so there is no attic ridge.

**Comment by shorowit** [comment]
@gjko Does that fix your issue?

**Comment by gjko** [comment]
@shorowit Sorry, but I could not make work the new `rake update_resources`.

**Comment by shorowit** [comment]
Sorry, I just pushed some changes to require OpenStudio 2.0.4. You can install this version from https://www.openstudio.net/developers. If you have it installed and you still can't get `rake update_resources` to work, please post the error message here.
