### ISSUE TITLE
Workflow suggestion for Orientation

### ISSUE THREAD

**Issue by gjko** [NREL/OpenStudio-BEopt#135]
I suggest moving the Orientation at the end of the Geometry group.

Actually, if you change orientation, it is a little bit confusing on which side the Door and the Windows are applied.

**Comment by shorowit** [comment]
I'm not clear on how you suggestion helps. Doors/windows are specified in terms of the building front/back/left/right facades. The building orientation specifies which cardinal direction the front of the building faces.

**Comment by gjko** [comment]
Uhm.. maybe it is only confusing for me. While using the measures I was wondering if the front is the south facade or not. So I preferred to change the orientation at the end, but anyway you can do it whenever you want.

**Comment by shorowit** [comment]
It shouldn't really matter if the orientation is done second, as the two measures should be independent of each other. If you find that not to be true, or if you have suggestions on how to clarify things so it's less confusing, please let us know.
