### ISSUE TITLE
Window Construction fails due to Location

### ISSUE THREAD

**Issue by gjko** [NREL/OpenStudio-BEopt#136]
The Window Construction measure fails because could not find the weather file.

![err_construction_windows](https://cloud.githubusercontent.com/assets/14098958/23811150/5d9385b0-059a-11e7-859f-9378356af6be.JPG)

```

in.rb:439:in `<main>': Error encountered. See result.ossr. (RuntimeError)

Script executing from: C:/Users/X/AppData/Local/Temp/OpenStudio.D10048/ApplyMeasureNow/UserScript
Found argument 'ufactor' with value '0.37'.
Found argument 'shgc' with value '0.3'.
Found argument 'heating_shade_mult' with value '1'.
Found argument 'cooling_shade_mult' with value '0.7'.
Found UserScript 'Set Residential Window Construction'.
result = false
Processed 1 base script and 0 merged scripts
```

**Comment by shorowit** [comment]
Can you attach your .osm? I think you'll need to rename it to .txt.

**Comment by gjko** [comment]
I think is this, I'm not entirely sure.

https://dl.dropboxusercontent.com/u/57865659/AF_SeedModel_v2_2.Geometry.osm

**Comment by shorowit** [comment]
Unfortunately the file is no longer available at the above link. If you can provide the file again, please reopen the ticket.
