### ISSUE TITLE
HPXML to OSM geometry

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#138]
- [x] @shorowit points to following resources for modeling in 2D
  - [x] https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/sdd/ReverseTranslator.cpp
  - [x] https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/sdd/MapGeometry.cpp
- [x] @macumber to copy @joseph-robertson on email about creating pinwheel geometry
  - [x] Scott Criswell points to `CMX_GeneratePolyLoops_CECNonRes()` in the [BEMCmpMgrCom module](https://github.com/CBECC-software/cbecc/blob/master/src/BEMCmpMgr/BEMCmpMgrCom.cpp)

**Comment by joseph-robertson** [comment]
Issues:
- [ ] Orientations of above-grade walls; get from attached windows?
- [ ] How to assign space volume; need for airflow measure

**Comment by joseph-robertson** [comment]
- [ ] Require weather file path (remove epw lookup)
- [ ] Allow mobile homes
- [ ] Update measure calls to look like Scott's
- [ ] Clean up geometry portion (make more hierarchical)
- [ ] Hot water, lighting, appliances, misc - RESNET-specific measures that differ from ours
- [ ] Mods to measures - e.g., wall construction to handle more than one set of properties for multiple walls
- [ ]

**Comment by shorowit** [comment]
Will address as part of #154
