### ISSUE TITLE
Use appropriate HVAC priority

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#139]
@jmaguire1 will provide the list to @joseph-robertson for implementation.

**Comment by jmaguire1** [comment]
Here's the priority list for ZoneHVAC equipment in the living space. If any of these aren't in the home, then skip them. They're listed by what they physically are with the E+ object that needs to go into the ZoneHVAC:Equipment list in ():

1. ERV (ZoneHVAC:EnergyRecoveryVentilator)
2. MSHP (ZoneHVAC:TerminalUnit:VariableRefrigerantFlow)
3. Baseboard (ZoneHVAC:Baseboard:Convective:Electric)
4. Boiler (ZoneHVAC:Baseboard:Convective:Water)
5. Forced air equipment other than MSHP (AirTerminal:SingleDuct:Uncontrolled)
6. Dehumidifier (ZoneHVAC:Dehumidifier:DX)
7. Room AC (ZoneHVAC:WindowAirCOnditioner)

**Comment by shorowit** [comment]
@joseph-robertson I suggest we create a method in hvac.rb that looks at what ZoneHVAC components are used and updates their priority according to the list @jmaguire1 provided.
