### ISSUE TITLE
Update skeletal unit tests

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#140]
Update unit tests that only check for Success but don't test objects/values. 

Measures:
- [x] PV
- [x] Airflow
- [x]  HVAC

**Comment by joseph-robertson** [comment]
Measures:
- [ ] PV
- [ ] Airflow

**Comment by shorowit** [comment]
I will provide a list of important HVAC object properties to test.

**Comment by shorowit** [comment]
@joseph-robertson I think simply looking at Efficiency/COP values for coils, as well as capacities (when not autosized) would be fine.
