### ISSUE TITLE
ResidentialHotWaterFixtures: bath incorrectly named

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-BEopt#147]
https://github.com/NREL/OpenStudio-BEopt/blob/master/measures/ResidentialHotWaterFixtures/measure.rb#L311

     sch_b = HotWaterSchedule.new(model, runner, Constants.ObjectNameSink + " schedule", Constants.ObjectNameSink + " temperature schedule", nbeds, sch_unit_index, "Bath", mixed_use_t, File.dirname(__FILE__))

Should be [ObjectNameBath](https://github.com/NREL/OpenStudio-BEopt/blob/master/resources/constants.rb#L429)

**Comment by shorowit** [comment]
https://github.com/NREL/OpenStudio-BEopt/commit/ec4399a028e56d5cb96dabc643434f48cfa39483
