### ISSUE TITLE
Ceiling Fan measure error

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#149]
[data_point.zip](https://github.com/NREL/OpenStudio-BEopt/files/957048/data_point.zip)

```
   ** Severe  ** Problem found in EMS EnergyPlus Runtime Language.
   **   ~~~   ** Erl program name: RESIDENTIAL_CEILING_FAN_SCHEDULE_PROGRAM
   **   ~~~   ** Erl program line number: 3
   **   ~~~   ** Erl program line text: ELSEIF RESIDENTIAL_CEILING_FAN_TIN_SENSOR < 24.389
   **   ~~~   ** Error message:  *** Error: EvaluateExpression: Variable = 'RESIDENTIAL_CEILING_FAN_TIN_SENSOR' used in expression has not been initialized! *** 
   **   ~~~   **  During Warmup, Environment=RUN PERIOD, at Simulation time=01/01 00:00 - 00:10
```

**Comment by joseph-robertson** [comment]
@shorowit could this be related to the HPWH measure deleting EMS sensors?

**Comment by shorowit** [comment]
I think it was still happening when I commented out all the HPWH foo.remove statements.

**Comment by joseph-robertson** [comment]
Hmm... ok. Also, looks like the heat pump water heater measure is called before the ceiling fan measure. I'm having trouble reproducing this error.

**Comment by shorowit** [comment]
Yeah, it happened in lots of files so I may not have picked the identical one. Looks like 23.278 in this err file.

**Comment by joseph-robertson** [comment]
Nvm, I was able to reproduce it. It is related to the heat pump water heater measure. I suspect it has to do with both measures trying to create sensors with the same output variable (Zone Mean Air Temperature).

**Comment by joseph-robertson** [comment]
In the hpwh, ceiling fan, and airflow measures, I took the approach of writing output variables only if they don't exist. There is no removing of output variables once they are written. Output variable objects can be shared amongst sensors.
