### ISSUE TITLE
OSM to HPXML export

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#152]
How to back out:
- Site
  - [ ] Address1
  - [ ] CityMunicipality
  - [ ] StateCode
  - [ ] ZipCode
- BuildingConstruction
  - [ ] NumberofStoriesAboveGrade
- AirInfiltration
  - [ ] OK to get properties, e.g. ELA, from BuildingUnit Features?
- Wall
  - [x] WallType
  - [x] Thickness
  - [ ] Studs/Spacing
  - [ ] Studs/FramingFactor
  - [ ] Color
  - [ ] Insulation/InsulationGrade
  - [ ] Insulation/Layer/InstallationType
  - [ ] Insulation/Layer/NominalRValue
  - [ ] Insulation/Layer/Thickness
  - [ ] CMU furring cavity?
- Roof
  - [ ] `<Roof>` vs `<Attic/<AtticType>cathedral ceiling`
  - [ ] RoofColor
  - [ ] RadiantBarrier
- Window
  - [ ] SHGC (i.e., shade multipliers)
  - [ ] Overhangs/Depth
  - [ ] Overhangs/DistanceToTopOfWindow
  - [ ] Overhangs/DistanceToBottomOfWindow
- Door
  - [x] RValue
- Foundation
  - [ ] FrameFloor/FloorJoists
  - [ ] FrameFloor/Insulation
  - [x] FoundationWall/Length
  - [x] FoundationWall/Height
  - [x] FoundationWall/Thickness
  - [x] FoundationWall/BelowGradeDepth
  - [ ] Slab/Perimeter
  - [x] Slab/ExposedPerimeter
  - [ ] Slab/PerimeterInsulationDepth
  - [ ] Slab/UnderSlabInsulationWidth
  - [x] Slab/DepthBelowGrade
- WaterHeating
  - [ ] EnergyFactor
  - [ ] RecoveryEfficiency
- HVACControl
  - [ ] Setpoint
  - [ ] Setup
  - [ ] Setback

- HVACPlant
  - [x] Air Source Heat Pump
  - [x] Mini Split Heat Pump
  - [x] Ground Source Heat Pump
  - [x] Furnace
  - [x] Boiler; condensing or non-condensing?
  - [x] Electric Baseboard
  - [x] Central Air Conditioner
  - [x] Room Air Conditioner
  - [ ] Dehumidifier
- Pools
  - [ ] Heater W
  - [ ] Pump W
- Lighting
  - [ ] LightingGroup W
  - [ ] Ceiling Fan; hpxml elements for efficiency, etc.?
- Appliances
  - [ ] Refrigerator RatedAnnualkWh
  - [ ] Dishwasher RatedAnnualkWh
  - [ ] ClothesWasher W
  - [ ] ClothesDryer W
  - [ ] CookingRange W
  - [ ] Freezer RatedAnnualkWh
  - [ ] Dehumidifier
- MiscGas
  - [ ] Fireplace
  - [ ] Grill
  - [ ] Lighting

**Comment by shorowit** [comment]
Moved to https://github.com/NREL/OpenStudio-ERI/issues
