### ISSUE TITLE
OSW to HPXML export

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#153]
This involves running the geometry-related measures first, and then pulling arguments for non-geometry measures for the osw arguments. List of hpxml variables for which it isn't clear what to assign:

- [ ] ACHnatural
- [ ] GaragePresent
- [ ] Year
- [ ] ClimateZone
- [ ] LongestPipeLength
- [ ] RatedFlowRate
- [ ] HoursInOperation
- [ ] UsedForWholeBuildingVentilation
- [ ] ElectricRate
- [ ] GasRate
- [ ] AnnualGasCost
- [ ] EfficiencyFactor
- [ ] HasTimerControl
- [ ] Capacity
- [ ] IsInduction
- [ ] IsConvection
- [ ] QualifyingLightFixturesInterior
- [ ] QualifyingLightFixturesExterior
- [ ] QualifyingLightFixturesGarage
- [ ] Cooling / Heating Capacity for 2/var speed systems?
- [ ] Cooling SHR for 2/var speed systems?
- [ ] Dehumidifier in schema?
- [ ] Finished attic is cape cod?
- [ ] Siding type and color?
- [ ] Must have a clothes dryer?
- [ ] Thickness of slab continuous insulation?
- [ ] Foundation wall interior studs framing factor?
- [ ] Would crawlspace walls ever have cavity insulation?
- [ ] Assume cavity insulation thickness to be equal to stud thickness?
- [ ] Finished basement slab properties?
- [x] Eaves to Enclosure extension
- [x] Dehumidifier to HVAC extension

**Comment by shorowit** [comment]
I suggest using beopt_to_hpxml.py as a reference.

**Comment by joseph-robertson** [comment]
@shorowit `thick_in2` not provided for measures `ResidentialConstructionsCeilingsRoofsThermalMass`, `ResidentialConstructionsWallsExteriorThermalMass`

**Comment by shorowit** [comment]
Moved to https://github.com/NREL/OpenStudio-ERI/issues
