### ISSUE TITLE
Not sure about the deration for missing insulation in cavity (ResidentialConstructionsCeilingsRoofsUnfinishedAttic)

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-BEopt#156]
I'm using the `ResidentialConstructionsCeilingsRoofsUnfinishedAttic` measure and I think the resulting construction is abnormally derated.

Tracking it down:

https://github.com/NREL/OpenStudio-BEopt/blob/master/measures/ResidentialConstructionsCeilingsRoofsUnfinishedAttic/measure.rb#L231

https://github.com/NREL/OpenStudio-BEopt/blob/master/resources/util.rb#L402
```ruby
def self.AirCavityOpen(thick_in)
        return self.new(name=nil, thick_in=thick_in, mat_base=nil, k_in=10000000.0, rho=Gas.Air.rho, cp=Gas.Air.cp)
end
```

Isn’t that `k_in` too extreme?

On the cavity layer, when you have wood, insulation, and gaps (grade III = 5% missing for example), this ends up derating the R-value by a ton

For example, I have setup a case like so:

```ruby
uACeilingInsRvalueNominal = 8.23
uACeilingInstallGrade = 3
uACeilingInsThickness = 3.94
uACeilingFramingFactor = 0.07
uACeilingJoistHeight = 5.0
uARoofInsRvalueNominal = 0
(uARoofInstallGrade = 1
uARoofInsThickness = 0
uARoofFramingFactor = 0.07
uARoofFramingThickness = 7.25)
```

Later on, I end up in this:

Dealing with layer 1
It has 3 layers in parallel
Material 0 - R_value = 6.246876561719141 - frac 0.07 
Material 1 - R_value = 8.23 - frac 0.8835 
Material 2 - R_value = 5.0e-07 - frac 0.0465 
Total parallel path R_value = 1.0752674464492638e-05 | U_value = 93000.11855675431

Current with gaps:

```ruby
In [1]: 1/(0.07 / 6.246876561719141 + 0.8835 / 8.23 + 0.0465 / 5.0e-07)
Out[2]: 1.0752674464492638e-05
```

```ruby
In [2]: 1/(0.07 / 6.246876561719141 + 0.8835 / 8.23 + 0 / 5.0e-07)
Out[2]: 8.434778817879955 (edited)
```

R-8.43 with no gaps, with grade `III` (5% missing) I end up with 1.07e-5, effectively R-0.

I cannot believe that 5% of missing insulation is like 100% of missing insulation.

----

To go further, I'm not sure I understand how to resulting construction's Rvalue is calculated (I might just be ignorant there...)

In https://github.com/NREL/OpenStudio-BEopt/blob/master/resources/util.rb#L942

If you replace this line by:

```ruby
puts "r_overall = #{r_overall}"
puts "layer_rvalues[curr_layer_num] = #{layer_rvalues[curr_layer_num]}"
puts "sum_r_all_layers = #{sum_r_all_layers}"
puts "sum_r_parallel_layers = #{sum_r_parallel_layers}"

# Material R-value
# Apportion R-value to the current parallel path layer
mat.rvalue = layer_rvalues[curr_layer_num] + (r_overall - sum_r_all_layers) * layer_rvalues[curr_layer_num] / sum_r_parallel_layers

puts "\n"
puts "mat.rvalue = layer_rvalues[curr_layer_num] + (r_overall - sum_r_all_layers) * layer_rvalues[curr_layer_num] / sum_r_parallel_layers"
puts "mat.rvalue = #{layer_rvalues[curr_layer_num]} + (#{r_overall} - #{sum_r_all_layers}) * #{layer_rvalues[curr_layer_num]} / #{sum_r_parallel_layers}"
puts "mat.rvalue = #{mat.rvalue}"
```

This is the output:

r_overall = 8.436887705532717
layer_rvalues[curr_layer_num] = 1.0752674464492638e-05
sum_r_all_layers = 1.9799747555542342
sum_r_parallel_layers = 1.0752674464492638e-05

mat.rvalue = layer_rvalues[curr_layer_num] + (r_overall - sum_r_all_layers) * layer_rvalues[curr_layer_num] / sum_r_parallel_layers
mat.rvalue = 1.0752674464492638e-05 + (8.436887705532717 - 1.9799747555542342) * 1.0752674464492638e-05 / 1.0752674464492638e-05
mat.rvalue = 6.456923702652947

I don't understand how r-value is "apportioned" there.

Going back to chapter 27 of ASHRAE Handbook of Fundamentals, 

![screen shot 2017-05-31 at 4 52 40 pm](https://cloud.githubusercontent.com/assets/5479063/26638220/e385fac8-4621-11e7-92d3-0cfdd8cfb91e.png)

So, given case C here, the equivalent resistance of the "layer" where R1 and R2 are in parallel is:

`R_avs = 1/((1/R1) + (1/R2))`

`R_avs` is what you call both `sum_r_parallel_layers` and `layer_rvalues[curr_layer_num]` 
I'm pretty sure the current setup doesn't allow to have more than one layer with parallel materials so they'll always be the same value... Otherwise `@path_frac` would need to be a list of list

The total equivalent resistance to schema B (parallel path) is called `Rp`, which is what you call you call `r_overall`

`Rp = 1 / ( 1/(Ra+ R1+Rb) + 1/(Ra+R2+Rb) )`

The total equivalent resistance to schema C (isothermal plane) is called `Rt`. This is what you call `sum_r_all_layers`

`Rt = Ra + R_avs + Rb`

Then you appear to be doing:

`mat.rvalue = R_avs + Rp - Rt`

And that implies:

`<=> mat.rvalue = Rp - Ra - Rb`

I guess I can follow that you basically add a couple of things in your construction above and below, do a parallel path calculation, and then remove these values, which makes sense if you're after the parallel path calculation indeed. I'm just not sure why your code is setup in such as complicated way.

**Comment by shorowit** [comment]
I'm not sure I'm fully understanding your question(s).

If I use
```
    args_hash["ceil_r"] = 8.23
    args_hash["ceil_grade"] = "I"
    args_hash["ceil_ins_thick_in"] = 3.94
    args_hash["ceil_ff"] = 0.07
    args_hash["ceil_joist_height"] = 5.0
```
I get an assembly R-value of 10.04.

If I use the same as above but with grade "III", I get an assembly R-value of 8.44.

I get similar values when I define the wall in REM/Rate.

**Comment by shorowit** [comment]
FYI, you can see the assembly R-value (and the underlying layer properties used in its calculation) by [uncommenting these lines](https://github.com/NREL/OpenStudio-BEopt/blob/master/measures/ResidentialConstructionsCeilingsRoofsUnfinishedAttic/resources/util.rb#L705-L707).

**Comment by shorowit** [comment]
I think it's working as intended. Please reopen this issue if you're still concerned.
