### ISSUE TITLE
OpenStudio-BEopt randomly fails sometimes

### ISSUE THREAD

**Issue by awcassidy** [NREL/OpenStudio-BEopt#158]
For some reason, running the same .osw file twice (from the command line) can succeed one time and fail another. Why would this be? My workflow.osw file is in h332.txt (just need to change extension) and the two out.osw files generated are in outh552 and outh332.

[h332.txt](https://github.com/NREL/OpenStudio-BEopt/files/1109860/h332.txt)
[outh552.txt](https://github.com/NREL/OpenStudio-BEopt/files/1109855/outh552.txt)
[outh332.txt](https://github.com/NREL/OpenStudio-BEopt/files/1109856/outh332.txt)

**Comment by shorowit** [comment]
@macumber  What does it mean when the two out.osw's attached above show that all the measures ran successfully, but one shows `"completed_status" : "Success",` and the other shows `"completed_status" : "Fail",`? Where would one find the reason for the failure?

**Comment by macumber** [comment]
The first thing would be to check all steps in the out.osw for step errors.  Second would be to look in run.log

**Comment by macumber** [comment]
I wonder if this issue is due to running the simulations in a Dropbox location, I believe there may be additional file access issues that can occur in drop box locations

**Comment by awcassidy** [comment]
Hi Dan and Scott,
Thanks so much for the replies. I'll try to reproduce the issue in a
non-Dropbox location.
Alecia

**Comment by awcassidy** [comment]
Hi Dan and Scott,
I couldn't reproduce the problem in a non-Dropbox folder. You're probably
right that it's Dropbox that is causing the issue. Thanks so much for
letting me know about the file access issues that could screw up OpenStudio!
Alecia

**Comment by shorowit** [comment]
Great to hear that fixed your issue!
