### ISSUE TITLE
Construction measures modifications

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#159]
- [ ] Add (sub)surface argument to, and update unit tests for:
  - [x] ResidentialConstructionsWallsExteriorWoodStud
  - [x] ResidentialConstructionsWindows
    - Sub surface arguments are now auto (all), each of the four facades, and individual sub surfaces
  - [x] ResidentialConstructionsFoundationsFloorsSlab
  - [x] ResidentialConstructionsDoors
  - [ ] ResidentialConstructionsCeilingsRoofsUnfinishedAttic
    - @shorowit: Something going on with roof insulation and specifically UATrussandIns material
  - [x] ResidentialConstructionsCeilingsRoofsFinishedRoof
  - [x] ResidentialConstructionsCeilingsRoofsRadiantBarrier
  - [ ] ResidentialConstructionsFoundationsFloorsBasementFinished
    - @joseph-robertson: Need to refactor 301 code
    - @shorowit: Surface argument doesn't include ceiling but other arguments do (i.e., framing factor and joist height)?
  - [ ] ResidentialConstructionsFoundationsFloorsBasementUnfinished
    - @joseph-robertson: Need to refactor 301 code
  - [ ] ResidentialConstructionsFoundationsFloorsCrawlspace
    - @joseph-robertson: Need to refactor 301 code
  - [ ] ResidentialConstructionsFoundationsFloorsPierBeam
    - For unit test material property values, not finding like objects in BEopt idfs...
  - [ ] ResidentialConstructionsFoundationsFloorsInterzonalFloors
    - @shorowit: Uninsulated option appears to differ from BEopt
    - @shorowit: How would you ever get floor over ambient?
  - [x] ResidentialConstructionsWallsInterzonal
  - [x] ResidentialConstructionsWallsExteriorGeneric
  - [x] ResidentialConstructionsWallsSheathing
  - [x] ResidentialConstructionsWallsExteriorFinish
  - [ ] ResidentialConstructionsFoundationsFloorsCovering
     - @joseph-robertson: Need to handle floor vs roofceiling name
     - @shorowit: Something weird going on with retrofit unit test
     - @shorowit: see fixme in 301 measure
  - [x] ResidentialConstructionsCeilingsRoofsRoofingMaterial
  - [x] ResidentialConstructionsCeilingsRoofsSheathing
  - [ ] ResidentialConstructionsCeilingsRoofsThermalMass
     - @joseph-robertson: Need to handle floor vs roofceiling name
     - @shorowit: see fixme in 301 measure
  - [ ] ResidentialConstructionsFoundationsFloorsSheathing
     - @joseph-robertson: Need to handle floor vs roofceiling name
     - @shorowit: see fixme in 301 measure
  - [ ] ResidentialConstructionsFoundationsFloorsThermalMass
     - @joseph-robertson: Need to handle floor vs roofceiling name
  - [x] ResidentialGeometryOverhangs
    - @shorowit: looks like the 301 measure drops the overhangs element in both the reference and rated XMLs? (therefore this measure is never applied)
  - [x] ResidentialConstructionsUninsulatedSurfaces
  - [x] ResidentialConstructionsWallsExteriorThermalMass
- [ ] Unit tests for @shorowit to check:
  - [ ] ResidentialConstructionsDoors
  - [ ] ResidentialConstructionsCeilingsRoofsUnfinishedAttic
  - [ ] ResidentialConstructionsCeilingsRoofsRadiantBarrier
  - [ ] ResidentialConstructionsFoundationsFloorsInterzonalFloors
  - [ ] ResidentialConstructionsWallsInterzonal
  - [ ] ResidentialConstructionsFoundationsFloorsPierBeam
  - [ ] ResidentialConstructionsUninsulatedSurfaces
- [x] Modify 301 measures hash (switch to array)

**Comment by shorowit** [comment]
Moved to https://github.com/NREL/OpenStudio-ERI/issues

**Comment by shorowit** [comment]
Oops, this should remain here.
