### ISSUE TITLE
Age of existing equipment and building

### ISSUE THREAD

**Issue by awcassidy** [NREL/OpenStudio-BEopt#160]
Does anyone know how to enter the age of existing equipment for the various HVAC measures? The measures seem to be missing this input which is in BeOpt. And also, which measure can be used to change the age of the building? I was under the understanding that BeOpt used age of building to get typical leakage estimates.

**Comment by shorowit** [comment]
In BEopt, the ages of existing equipment were only used for life-cycle analysis -- i.e., calculating life-cycle costs and averaging of multiple energy simulations throughout the analysis period. (They did not result in equipment efficiency degradation, for example.) As the OpenStudio measures are only used for developing a single energy simulation, those inputs do not apply.

In BEopt, the age of the building was used for two purposes. 
1. It was used to apply the ASHRAE 62.2 infiltration credit. (In our Airflow measure, the "Mechanical Ventilation: Is Existing Home" argument serves the same purpose.). 
2. The input was used to display a typical leakage estimate value that the user could then select if they so wanted to. I guess we could allow an infiltration rate of "auto" in our OpenStudio measure that uses that algorithm, but currently have not done so.

**Comment by awcassidy** [comment]
Hi Scott,

Thanks so much for your message.

I guess I was confused because I thought that equipment efficiency
degradation was indeed being used to get degradation factors in Beopt:
"Degradation factors for existing installed equipment (based on age and
maintenance factor)" is listed as a feature on this website:
https://beopt.nrel.gov/BEoptChangelog. Was it previously available but then
cut from later versions of BeOpt? If it was, is there a way I can figure
out how it was done so that I can input the correct degradation factors
based on the equipment ages?

Thanks!

Alecia

**Comment by shorowit** [comment]
Ah. Indeed it was added and then subsequently removed. @ejhw will have to provide more info.

**Comment by awcassidy** [comment]
Thanks, Scott!

**Comment by ejhw** [comment]
@awcassidy The reasoning behind removing the degradation factors from the Building America House Simulation Protocols is explained below. Also perhaps of interest is this report on AC maintenance: http://www.nrel.gov/docs/fy13osti/56283.pdf

> We looked into this a while ago and decided to remove all of the age degradation factors in BEopt 2.0 and the current Addendum to the House Simulation Protocols (HSP), after finding little substantial evidence in the literature for degradation of most types of equipment. We'll continue to discuss this topic over the next year as part of the HSP revisions.
> 
> From what I can tell, the age degradation factors for furnaces and boilers in the HSP were loosely based on numbers from:
> 
> E-­Source. (1993). Space Heating Technology Atlas. Boulder, CO: E-­Source Inc.
> 
> If I remember correctly, that document stated that oil boiler efficiency would decline 2% per year without maintenance. I think that, lacking better data, that degradation rate was incorrectly applied to gas furnaces and water heaters as well. So I'm not surprised by your findings. As you might be aware, Navigant did testing on old gas and electric water heaters and found no discernible evidence of degradation. PARR just finished up testing of 10 gas furnaces that came back from the field after 20+ years of service and we are finding almost no degradation in efficiency over time.

**Comment by awcassidy** [comment]
Thanks so much, Eric. This was super helpful!
