### ISSUE TITLE
Sizing measure creates new SpaceType object for some unit tests

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#164]
Testing hvac sizing measure on new osm files created from the geometry editor; some unit tests result in a new SpaceType object that is not attached to anything. (?)
- test_equip_ASHP_one_speed_autosize_min_temp
- test_equip_gas_furnace_autosize
- test_equip_gas_furnace_and_room_air_conditioner_autosize
- test_loads_2story_crawlspace_garage_finished_attic_ducts_in_garage
- test_equip_gas_furnace_and_ac_one_speed_fixedsize
- test_equip_ASHP_one_speed_autosize_for_max_load_min_temp
- test_loads_2story_unfinished_basement_garage_finished_attic_ducts_in_unfinished_basement
- test_loads_1story_pierbeam_unfinished_attic_vented_ducts_in_unfinished_attic
- test_equip_ASHP_two_speed_fixedsize
- test_equip_electric_furnace_and_ac_two_speed_fixedsize
- test_equip_ASHP_one_speed_fixedsize
- test_equip_gas_furnace_and_ac_one_speed_autosize
- test_equip_electric_furnace_and_ac_two_speed_autosize
- test_loads_1story_pierbeam_unfinished_attic_vented_ducts_in_pierbeam
- test_loads_2story_finished_basement_garage_finished_attic_ducts_in_fininshed_basement
- test_equip_gas_furnace_and_room_air_conditioner_fixedsize
- test_equip_gas_furnace_and_ac_variable_speed_autosize
- test_equip_ASHP_one_speed_autosize
- test_equip_ASHP_two_speed_autosize
- test_equip_GSHP_autosize
- test_equip_ASHP_variable_speed_fixedsize
- test_equip_GSHP_fixedsize
- test_equip_gas_furnace_and_ac_variable_speed_fixedsize
- test_equip_ASHP_variable_speed_autosize
- test_equip_gas_furnace_fixedsize

**Comment by shorowit** [comment]
It's caused by [this line](https://github.com/NREL/OpenStudio-BEopt/blob/space_types/resources/geometry.rb#L504) being called on the ducts dummy space.  Because you're setting space.isPlenum=true for the ducts dummy space (why?), OS is automatically returning the plenum space type for the space.

**Comment by joseph-robertson** [comment]
@shorowit, not sure I understand. Are you talking about the `ra_duct_space` object? Where am I setting space.isPlenum=true?

**Comment by shorowit** [comment]
It's happening due to [this line](https://github.com/NREL/OpenStudio-BEopt/blob/space_types/measures/ResidentialAirflow/measure.rb#L1523).

**Comment by joseph-robertson** [comment]
Yep. I'll just put a check for `isPlenum` in the `space_is_finished` method.
