### ISSUE TITLE
Update eaves measure to handle custom geometry

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#165]
Generalize this measure away from no garage or garage always on left/right, how to determine inset position, etc.

**Comment by joseph-robertson** [comment]
Approach 1: use the `addOverhang()` method, and then additionally tranformation(s) (e.g., stretch) to the overhangs to make them "eaves".

**Comment by joseph-robertson** [comment]
Approach 2: collect all highest roof vertices and create one shading object that follows the perimeter of the whole house.

**Comment by joseph-robertson** [comment]
Ugh. This is hard. Need some guidance or suggestions. @shorowit?

**Comment by joseph-robertson** [comment]
![image](https://user-images.githubusercontent.com/8516790/29381733-82fcc694-8287-11e7-8662-9552a72bfbee.png)
Almost there. Still need to:
- [ ] Not add those eaves under the roof decks
- [ ] Not have eaves overlap each other
- [ ] Stretch eaves to fill in missing gaps
- [ ] Have all eaves extend from roof decks perpendicularly

**Comment by shorowit** [comment]
No longer applicable.
