### ISSUE TITLE
Window/Door Area retrofits

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#168]
If you take an existing osm and run the window areas or door area measures, you are then required to run the window construction or door construction measures. I suggest we instead try to preserve the construction assignments like so:

- Window Areas: Before removing windows, obtain their constructions. 
  - If a single construction is used for all windows, assign it to the new windows
  - If a single construction is used for each facade, re-assign them to the new windows based on facade
  - Any other situation; don't assign a construction (as is the case now)
- Door Area: Before removing doors, obtain their constructions.
  - If a single construction is used for all doors, assign it to the new doors
  - Any other situation; don't assign a construction (as is the case now)

Please also add unit tests for these situations.

**Comment by shorowit** [comment]
Hmm, this doesn't seem to be working correctly for window areas. Try this OSW on this OSM:
[measures.osw.txt](https://github.com/NREL/OpenStudio-BEopt/files/1239200/measures.osw.txt)
[resstock.osm.txt](https://github.com/NREL/OpenStudio-BEopt/files/1239202/resstock.osm.txt)

Results in errors like:
```
   ************* IDF Context for following error/warning message:
   ************* Note -- lines truncated at 300 characters, if necessary...
   *************    960 FenestrationSurface:Detailed,
   ************* indicated Name=Surface 5 - Window 1
   ************* Only last 3 lines before error line shown.....
   *************    961   Surface 5 - Window 1,                   !- Name
   *************    962   Window,                                 !- Surface Type
   *************    963   ,                                       !- Construction Name
   ** Severe  ** IP: IDF line~963 Error detected in Object=FENESTRATIONSURFACE:DETAILED, name=SURFACE 5 - WINDOW 1
   **   ~~~   ** Field [Construction Name] is required but was blank
```

**Comment by joseph-robertson** [comment]
When I tried that OSW on that OSM, it ran successfully...

**Comment by joseph-robertson** [comment]
When I tried that OSW on that OSM, it ran successfully...

**Comment by shorowit** [comment]
Hmm, I must have been on the wrong commit. Works for me now, sorry.
