### ISSUE TITLE
Multizone modeling

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#171]
Which additional space types to include:
- [ ] `kitchen`?
- [ ] `bedroom`?
- [ ] `bathroom`?
- [ ] `livingroom` as opposed to `living` (then what would `living` apply to)?

Other notes:
- [ ] Any updates needed for MELs, lighting, appliances, etc.?
- [ ] Updates to hot water
- [ ] HVAC discussion pending
- [ ] @jonwinkler to advise @joseph-robertson on how to proceed with multizone changes per HSP assumptions
- [ ] What do we do about airflow while we're not yet using the AFN approach?

Testing method:
- [ ] Create new floorplan.json file(s) with multizone geometry
- [ ] Incorporate osm into OpenStudio-BEopt workflow
- [ ] Update logic for how objects are assigned to (new) space types

**Comment by joseph-robertson** [comment]
Testing notes:
- Slab measure works for geometries with 2+ slab surfaces?

**Comment by joseph-robertson** [comment]
Proposed logic for assigning appliances to spaces:
- [ ] List all spaces and space types as possible argument values
- [ ] Also include 'auto' as a possible argument value
- [ ] If user chooses space, assign appliance to that space
- [ ] If user chooses space type, assign appliance to a space of that space type
- [ ] If user chooses 'auto', assign appliance to a space of the kitchen space type (error out if there is no kitchen space type)

**Comment by shorowit** [comment]
Remember that spaces and space types can have the same name, so the argument choices will have to include "space" or "space type".

**Comment by joseph-robertson** [comment]
Notes:
- "living - generic" space type?
- double-check that object would go into below-grade, e.g., basement of multifamily building

**Comment by joseph-robertson** [comment]
Measure checklist:
- [x] ResidentialGeometryFromEditor
- [x] ResidentialApplianceRefrigerator
- [x] ResidentialHotWaterHeaterTankFuel
- [x] ResidentialApplianceClothesWasher

**Comment by jonwinkler** [comment]
See attached spreadsheet as a starting point.

[multizone_spacetypes.xlsx](https://github.com/NREL/OpenStudio-BEopt/files/1257453/multizone_spacetypes.xlsx)

**Comment by joseph-robertson** [comment]
Thanks @jonwinkler

Am I reading this right- the cooking range and dishwasher have preference to the 'laundry room'?

**Comment by jonwinkler** [comment]
@joseph-robertson , sorry, i must have accidentally deleted that. Updated version attached.

[multizone_spacetypes.xlsx](https://github.com/NREL/OpenStudio-BEopt/files/1260293/multizone_spacetypes.xlsx)

**Comment by shorowit** [comment]
Need to reconcile new water heater space type hierarchy with previous climate zone specific logic -- e.g., a separate hierarchy for each climate zone grouping.

**Comment by joseph-robertson** [comment]
@jonwinkler, can you attach the HSP?

**Comment by shorowit** [comment]
https://energy.gov/eere/buildings/downloads/building-america-2014-house-simulation-protocols

**Comment by joseph-robertson** [comment]
@jonwinkler, what is your interpretation of Table 9 from the HSP? I have your list from the spreadsheet, but remove garage from it for climate zones that aren't Hot-Humid or Hot-Dry. What do you think?

**Comment by jonwinkler** [comment]
I would give priority to the HSP recommendations. For hot dry and hot humid climates, the garage should be 1st priority, followed by my list (I guess?). For other climates, I think garage should be moved to end (or before the attic).
