### ISSUE TITLE
Propane furnace -> gas furnace upgrade error

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#173]
OSM has a propane furnace and room AC. Gas furnace measure is applied (room AC should remain).
[measures.osw.txt](https://github.com/NREL/OpenStudio-BEopt/files/1239247/measures.osw.txt)
[resstock.osm.txt](https://github.com/NREL/OpenStudio-BEopt/files/1239246/resstock.osm.txt)

Error is:
```
   ** Severe  ** GetPTUnit: ZoneHVAC:PackagedTerminalAirConditioner="RESIDENTIAL ROOM AC ZONE PTAC"
   **   ~~~   ** ..Air-conditioners air outlet node name must be the same as a zone inlet node name.
   **   ~~~   ** ..Zone inlet node name is specified in ZoneHVAC:EquipmentConnections object.
   **   ~~~   ** ..Air-conditioners outlet node name = NODE 25
```

**Comment by joseph-robertson** [comment]
@kbenne is investigating why the removal of the airloop disconnects the `ZoneHVACPackagedTerminalAirConditioner` from the zone.

**Comment by shorowit** [comment]
OS bug report: https://github.com/NREL/OpenStudio/issues/2787

**Comment by shorowit** [comment]
https://github.com/NREL/OpenStudio/commit/dc4a98f52375d59570a2a322669fa642b86725b6
