### ISSUE TITLE
Thermostat measure arguments

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-Beopt#19]
Need to revisit why Fans electricity consumption is so high for the equipment measures, and think about how we may fix this issue.

Below is screenshot of OpenStudio vs BEopt for Central Air Conditioner:

![image](https://cloud.githubusercontent.com/assets/8516790/13442126/f792ce5a-dfb7-11e5-9b3f-cf67a2993396.png)

**Comment by shorowit** [comment]
Currently:
1. The thermostat/season measure must be applied before the HVAC equipment measures.
2. The thermostat/season measure asks whether there is heating and cooling equipment. 
3. The heating and cooling equipment measures error out if no season object is found (as created by the thermostat/season measure).

Instead, I recommend:
1. The thermostat/season measure must be applied **after** the HVAC equipment measures
2. In the heating and cooling equipment measures, no longer assign the availability schedule to, e.g., the CoilHeatingElectric object. Have the thermostat/season measure assign the availability schedule to these objects.
3. Remove the thermostat/season measure arguments regarding the presence of heating and cooling equipment. (Yay!) 
4. Allow thermostat/season measure arguments for setpoints to be optional. Give an error if, e.g., heating setpoint provided but no heating equipment found or heating setpoint not provided by heating equipment found.
5. Split the thermostat/season measure into heating and cooling versions (2 measures).

This will significantly simplify our use of HVAC measures in ResStock/BPA Regional Tool.

Any objections? @joseph-robertson @jmaguire1 @ejhw

**Comment by joseph-robertson** [comment]
No objections. I'll begin trying to implement this.

**Comment by ejhw** [comment]
Sounds fine.

**Comment by joseph-robertson** [comment]
Re #5 above: What about the assignment of the ThermostatSetpointDualSetpoint? It sets both the heating and cooling setpoint schedules, and we'd want only one of these objects. Should we search for it if it exists, otherwise create it if it doesn't?

**Comment by shorowit** [comment]
Sounds like a good idea to me. I can't think of any downsides to that approach?

**Comment by ejhw** [comment]
Would this require retrofit measures like prog. or smart thermostat to be split into heating and cooling as well? Or could there be a meta measure that calls both the heating and cooling thermostat measures.

**Comment by shorowit** [comment]
A building retrofit doesn't have to be a single OpenStudio measure. You, or the software tool, would simply call both measures. No need to create some sort of meta-measure to call both for you.

**Comment by joseph-robertson** [comment]
@shorowit It appears that the `ThermostatSetpointDualSetpoint` object must have both the `HeatingSetpointTemperatureSchedule` and `CoolingSetpointTemperatureSchedule` set, in order to run successfully. So, in the heating setpoints measure I set a dummy (monthly_sch of 10000 representing no cooling equipment) cooling setpoint schedule if one has not already been set. Similarly in the cooling setpoints measure, I set a dummy (monthly_sch of -10000 representing no heating equipment) heating setpoint schedule if one has not already been set. These dummy setpoint schedules can then be reset to actual schedules when the heating or cooling setpoints measures are applied.

**Comment by shorowit** [comment]
This is great! It immediately dropped into ResStock without a hitch. Nice work @joseph-robertson. 

Your use of dummy schedules sounds fine to me; someday we could revisit this by getting `ThermostatSetpoint:SingleCooling` and `ThermostatSetpoint:SingleHeating` wrapped in OS if we really wanted to avoid this. But it's not a high priority.

One more Tstat-related request: Can we add Eric's logic from sim.py that handles cooling setpoints lower than heating setpoints (by using the average of the two) for the portion of the year where both heating and cooling is available? See lines 10139-10179 in sim.py in BEopt trunk.

**Comment by joseph-robertson** [comment]
@shorowit Yes I will add Eric's logic that handles cooling setpoints lower than heating setpoints.
