### ISSUE TITLE
Missing .dlls when trying to run OS 2.3

### ISSUE THREAD

**Issue by joshdr83** [NREL/OpenStudio-BEopt#199]
I keep getting a missing .dll file message that doesn't let OS restart and I have to reinstall... Using OS 2.3 with Windows 10 Pro. This happened with OS 2.2 as well...

**Comment by joshdr83** [comment]
![os23_missing_dlls](https://user-images.githubusercontent.com/3343052/31321144-b0762cd0-ac46-11e7-9ae7-3499bcd6662f.PNG)

**Comment by shorowit** [comment]
This is really a question for OpenStudio itself. I have reported the issue here:
https://github.com/NREL/OpenStudio/issues/2820
