### ISSUE TITLE
Break out individual appliances for timeseries reporting

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BEopt#212]
Proposed breakout:
- [x] Clothes dryer
- [x] Clothes washer
- [x] Range
- [x] Refrigerator
- [x] Dishwasher
- [x] Plug loads
- [x] Other (LULs, pools, spas, etc.)

For load modeling. Should we make this an argument so the breakout can be turned on or off?

cc @jmaguire1 @shorowit

**Comment by joseph-robertson** [comment]
Implemented in the timeseries measure. Argument added so the breakout can be turned on or off.
