### ISSUE TITLE
Utility bill calculation improvements

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#278]
Should set simulation start day of week to Monday for runs using TMY (I think the default is Thursday?), since SAM SDK assumes start day of Monday.

**Comment by shorowit** [comment]
We already made this change: https://github.com/NREL/OpenStudio-BEopt/blob/master/resources/location.rb#L104

**Comment by joseph-robertson** [comment]
@shorowit Nice. Who added that?
