### ISSUE TITLE
Consolidate location measures

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-Beopt#31]
Consolidate all measures related to location?
- [x] Set Residential Weather File
- [x] Set Residential Mains Water Temperature
- [x] Set Residential Ground Temperatures (Why EnergyPlus measure?)
- [x] Set Residential Sizing Period (Why EnergyPlus measure?)

cc @joseph-robertson @jmaguire1 @ejhw

**Comment by joseph-robertson** [comment]
Confirmed that this is fixed in 1.11.5.
