### ISSUE TITLE
Water heater location

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-Beopt#34]
We should implement the algorithm for automatically locating the water heater based on climate zone and available spaces (e.g., get_water_heater_location() method from BEopt's sim.py) and allow the user to choose this for the location.

**Comment by shorowit** [comment]
Committed by @jmaguire1: https://github.com/NREL/OpenStudio-Beopt/commit/909d4b93e0dbef928fee9d028ac83afb571e4ae9

Some small changes left to do.

**Comment by jmaguire1** [comment]
Final changes added in c1d2d2395ae1d7038339eac1acf8b1dcf21bc57b
