### ISSUE TITLE
Boiler pump operation

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#36]
Goal: Make sure boiler pump is behaving as is realistic.

Notes from Eric:
"I looked into the boiler pump issue a bit. We’re already using ‘intermittent’ for pump control. We were using ‘ConstantFlow’ for Boiler Flow Mode. Changing to ‘NotModulated’ didn’t change output.

I think this will take some more looking into. It isn’t clear to me what should be happening with pump run time; our workaround may not be correct. If the boiler is hitting the boiler loop setpoint of 180ºF, then the pump runtime should be longer than boiler runtime. However, if the zone setpoint is met before the boiler loop reaches 180ºF, then pump runtime should equal boiler runtime.

Things to look into:
• Check boiler loop temperature regarding comment about 180ºF setpoint above.
• Make sure the boiler loop water volume is large enough (boiler shouldn’t be short cycling all the time). Is the pump running constantly because the zone thermostat is not bang-bang, but the plant loop control is bang-bang?
• Make sure boiler isn’t modulating heat output. Maybe ‘Minimum Part Load Ratio’ should be 1 for non-modulating boilers (it is currently 0)?
This numeric field contains the minimum part load ratio. If the ratio of demand to boiler nominal capacity is less than the minimum part load ratio, then the Min PLR will determine the operating PLR. 
• Run with 1 min timestep and check timestep output to see if pump still runs during time steps when boiler is completely off. Check boiler runtime fraction; if less than 1, the pump runtime should be less than the full timestep."

Next steps:
- Jeff will look into energy impact of excluding BEopt EMS workaround. (Eric thinks it may be small and we could then ignore it.)

cc @ejhw @asparke2

**Comment by jmaguire1** [comment]
We have a decision, but there was a bug that prevented us from implementing.There's something strange with one case we were considering using significantly less energy while still maintaining load, so I have to do some detailed plant loop debugging. I'll try to wrap this one up this week.

**Comment by shorowit** [comment]
May also affect GSHP and SHW.

**Comment by shorowit** [comment]
@jmaguire1 let's make the same change on the BEopt side for consistency.

**Comment by jmaguire1** [comment]
They should be included in the latest commit to BEopt (although we'll have to add a new input variable for whether or not the boiler is modulating). I'll leave this open until that variable is added.

**Comment by shorowit** [comment]
I will hookup input in BEopt and then update HVAC sizing unit tests.
