### ISSUE TITLE
Airflow Measure

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#40]
Calculate volume, height, area, etc in idf. For use in the airflow measure so that we don't have to input these from the user.

**Comment by shorowit** [comment]
@joseph-robertson can start converting our EnergyPlus measure to an OpenStudio measure.

**Comment by shorowit** [comment]
Rename "ResidentialAirflow" to "ResidentialAirflowOriginalModel" and create new "ResidentialAirflow" measure.

**Comment by joseph-robertson** [comment]
Issues:
* Does not appear that ZoneInfiltrationFlowCoefficient is wrapped. Therefore cannot actuate the living zone infiltration using EMS.

**Comment by shorowit** [comment]
I think we can use [SpaceInfiltrationDesignFlowRate](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-1.13.0-doc/model/html/classopenstudio_1_1model_1_1_space_infiltration_design_flow_rate.html) for both issues? We're really only using a ZoneInfiltrationFlowCoefficient object so that we can override it's output and assign an infiltration flow rate via EMS calculations.

**Comment by joseph-robertson** [comment]
@shorowit Any thoughts on:

The NatVentTemp schedule varies by month between NatVentHtgSsnTempWeek, NatVentClgSsnTempWeek, and NatVentOvlpSsnTempWeek. Do we have a schedule class that can accommodate this?

**Comment by shorowit** [comment]
It's so unique that it's probably best to stick with a custom approach rather than try to build a helper class.

**Comment by joseph-robertson** [comment]
Reminder to bump the min OS version required once EMS is included in an OS release.

@shorowit

**Comment by shorowit** [comment]
:+1: 

Once EMS is in a release, I'll test it via ResStock.

**Comment by shorowit** [comment]
We'll also want to uncomment the unit tests at that point too.

**Comment by joseph-robertson** [comment]
TODO:
- [ ] zone mixer on return path - @jmaguire1

BEopt:
```
AirLoopHVAC:ReturnPath,
   Return Air Path_1,          !- Name
   Air Demand Outlet Node_1,   !- Return Air Path Outlet Node Name
   AirLoopHVAC:ReturnPlenum,   !- Component 1 Object Type
   Return Plenum_1;            !- Component 1 Name
``` 
vs OpenStudio:
```
AirLoopHVAC:ReturnPath,
  Central Air System_1 Return Path,       !- Name
  Node 6,                                 !- Return Air Path Outlet Node Name
  AirLoopHVAC:ReturnPlenum,               !- Component Object Type 1
  Air Loop HVAC Return Plenum 1,          !- Component Name 1
  AirLoopHVAC:ZoneMixer,                  !- Component Object Type 2
  Zone Mixer_1;                           !- Component Name 2
```

**Comment by joseph-robertson** [comment]
Right now, energy use is way way way higher with ducts than without ducts. Is this expected? Not sure what's going on.

@shorowit @jmaguire1

**Comment by shorowit** [comment]
Not sure what is "way" higher, but yes it should be higher with ducts.

**Comment by jmaguire1** [comment]
It's coming out something like 1000% higher, I can help with debugging.

**Comment by joseph-robertson** [comment]
Single-family detached, slab, two story, unfinished attic. Design alternatives on the airflow measure:
![image](https://cloud.githubusercontent.com/assets/8516790/19665782/05fceaf0-9a04-11e6-955b-eeb57c0bdbcf.png)

**Comment by shorowit** [comment]
@joseph-robertson Are you aware that the test_retrofit_infiltration unit test is giving an OpenStudio warning? "Attempt to write a disconnected WorkspaceObject out to Idf." Don't see it in any of the other unit tests.

**Comment by joseph-robertson** [comment]
Yes, this has something to do with removing schedules and leaving orphaned objects. I'm still looking into it.

**Comment by joseph-robertson** [comment]
Fixed it by changing "MechanicalVentilation" ruleset to "MechanicalVentilationSchedule" and "NatVent" ruleset to "NatVentSchedule".

**Comment by shorowit** [comment]
Around 2% of our simulations are getting E+ errors due to not being able to use SurfaceProperty:ConvectionCoefficients. @nmerket we will need you to wrap this object. OpenStudio does already wrap the [SurfaceProperty:ConvectionCoefficients:MultipleSurface ](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-1.13.2-doc/model/html/classopenstudio_1_1model_1_1_surface_property_convection_coefficients_multiple_surface.html)object, so hopefully it's not too big of a lift.

**Comment by joseph-robertson** [comment]
Looks like the lack of surface property convection coefficients causes errors when we try to model two/variable -speed AC/ASHP:

![image](https://cloud.githubusercontent.com/assets/8516790/20504377/4e7a492e-b004-11e6-9fb9-b63f386b407e.png)

**Comment by nmerket** [comment]
`SurfaceProperty:ConvectionCoefficients` is part of the latest OS iteration builds.

**Comment by shorowit** [comment]
@joseph-robertson will update the measure to use `SurfaceProperty:ConvectionCoefficients`.

**Comment by shorowit** [comment]
Completed. Needs testing. Requires OS 2.0.2.

**Comment by joseph-robertson** [comment]
I'm not seeing how the ERV gets added to the zone; need to test airflow measure for when the mechanical ventilation type is balanced, and add line `zone_hvac.addToThermalZone(unit.living_zone)` (if this is the appropriate code to add).

**Comment by shorowit** [comment]
For what it's worth, [ZoneHVACEnergyRecoveryVentilator](ZoneHVACEnergyRecoveryVentilator) inherits from [ZoneHVACComponent](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.0.4-doc/model/html/classopenstudio_1_1model_1_1_zone_h_v_a_c_component.html), which has methods [addToNode ](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.0.4-doc/model/html/classopenstudio_1_1model_1_1_zone_h_v_a_c_component.html#a0a48377b6e45b09a8d5311c354180648) and [addToThermalZone](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.0.4-doc/model/html/classopenstudio_1_1model_1_1_zone_h_v_a_c_component.html#a570dd3aa34553a03fdda399651aca87d).

**Comment by joseph-robertson** [comment]
Yes, addToThermalZone seemed to do the trick.
