### ISSUE TITLE
Water heater tasks

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-Beopt#41]
- [x] add water heater measure error if no tmains object found @jmaguire1 
- [x] consolidate tmains measure into location measure @shorowit
- [x] propane WH measures are missing @jmaguire1 
- [x] add realistic input power for tankless WHs (OS & BEopt) @jmaguire1 
- [x] add tankless propane WH @jmaguire1

**Comment by jmaguire1** [comment]
Propane water heaters added in c1d2d2395ae1d7038339eac1acf8b1dcf21bc57b
Realistic tankless input power added in 909d4b93e0dbef928fee9d028ac83afb571e4ae9

**Comment by shorowit** [comment]
@jmaguire1 Can we add a propane tankless WH measure too? we are using these in ResStock.

**Comment by jmaguire1** [comment]
Sure, no problem. Added to the list

**Comment by jmaguire1** [comment]
So as far as allowing the clothes washer/dishwasher measure before the water heater measure, the original issue was that the plant loop is created by the water heater measure. We could instead allow the CW/DW measures to create the plant loop, but the larger issue is that some of the calculations in those measures depend on the water heater setpoint. I'd say we probably don't want to allow CW/DW measures before the WH measure.

**Comment by shorowit** [comment]
Good point. There are some situations where WH setpoint isn't needed to model CW/DW, but no need to get super fancy here. I'll axe that request.

**Comment by jmaguire1** [comment]
closed via e9c7b24e05bdd55c534dd4a0e346e15792eb191f
