### ISSUE TITLE
Daylight saving time

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-Beopt#48]
David,
 
Question about the RunPeriodControlDaylightSavingTime object. When I set this in the osm:
 
OS:RunPeriodControl:DaylightSavingTime,
  {9e77f034-a0fd-4299-a6ce-8594998c51b6}, !- Handle
  4/7,                                    !- Start Date
  10/26;                                  !- End Date
 
It doesn’t seem to get translated in the idf:
 
RunPeriodControl:DaylightSavingTime,
  2nd Sunday in March,                    !- Start Date
  1st Sunday in November;                 !- End Date
 
Is there an additional change I need to make in the osm?
 
Thanks,
Joe

Dan, do you know the status of these issues.

https://github.com/NREL/OpenStudio/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+daylight+savings

The most recent one from few weeks ago describes just what Joe is seeing.
https://github.com/NREL/OpenStudio/issues/2185

David

**Comment by joseph-robertson** [comment]
For the following example, the start/end dates are different between the osm and idf.
[osm.zip](https://github.com/NREL/OpenStudio-Beopt/files/285289/osm.zip)
[idf.zip](https://github.com/NREL/OpenStudio-Beopt/files/285290/idf.zip)

Is there some other flag or indicator to switch in another object?

@macumber @shorowit

**Comment by macumber** [comment]
We are going to fix 2185 for OS 1.12

**Comment by joseph-robertson** [comment]
Confirmed that this is fixed in 1.11.5.
