### ISSUE TITLE
Crankcase heater

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#50]
Check latest BEopt implementation. Is EMS only used to change the output end use category? If so, we'd like to merge into AC/HP measures and get rid of the EnergyPlus measure.
cc @ejhw @jonwinkler

**Comment by jonwinkler** [comment]
EMS is used to address two issues, one of which is the issue you describe. See comment in def _processSystemCrankcaseHeater. But given we're switching over to AirLoopHVAC:UnitarySystem, I can't say if both issues will persist and it's possible we'll no longer need EMS for this. Worth testing.

**Comment by shorowit** [comment]
@jonwinkler is going to look into the other issue.

**Comment by jonwinkler** [comment]
When using a heating pump, the crankcase heater input and output is associated with the heating coil. But when we use an AC w/ a furnace, it's associated with the cooling coil. So the end-use will change based on the heating system type. Our EMS work around has the crankcase heater always show up under cooling.

Here's the EnergyPlus documentation on this:
If this cooling coil is used as part of an air-to-air heat pump the crankcase heater defined for this DX cooling coil is ignored and the crankcase heater power defined for the DX heating coil is enabled during the time that the compressor is not running for either heating or cooling.

**Comment by jonwinkler** [comment]
Verified that crankcase heaters work when using single and multi-speed heat pumps with AirLoopHVAC:UnitarySystem. However, they're metered with heating electricity. Air conditioner w/ gas furnace meters the crankcase with cooling.

Uncovered an issue when using a crankcase heater in a multi-speed air conditioner with a gas furnace. Created an EnergyPlus github issues here: [https://github.com/NREL/EnergyPlus/issues/5659](url)

**Comment by shorowit** [comment]
Thanks for investigating, Jon. Let's proceed with moving the crankcase heater into the AC/ASHP measures then.

**Comment by joseph-robertson** [comment]
So do I want to populate the CoilCoolingDXSingleSpeed (ASHP only) and CoilHeatingDXMultiSpeed objects with:
* Crankcase (in W) for the crankcaseHeaterCapacity input,
* CrankcaseMaxT (in deg C) for the maximumOutdoorDryBulbTemperatureforCrankcaseHeaterOperation input

?

Default Crankcase (in kW) in BEopt is 0.0 for multispeed ACs and 0.02 for all ASHPs. Crankcase Max Temp is 55 deg F.

@shorowit @jonwinkler

**Comment by joseph-robertson** [comment]
Talked with Jon on previous comment. Answer is yes.

Crankcase heater is modeled on heating coil for both single and multispeed ASHP since DXHeating is present, and on cooling coil when there is no DXHeating.

**Comment by shorowit** [comment]
Let's not worry about the metering issue. Only remaining issue therefore is the bug reported by Jon.. We'll work to get this fixed.

**Comment by shorowit** [comment]
Fixed according to https://github.com/NREL/EnergyPlus/issues/5659. Need to verify.

**Comment by shorowit** [comment]
Should be able to test the fix in OS 1.12.5 or 1.12.6 (E+ 8.6).
