### ISSUE TITLE
Multiple/Partial HVAC systems

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#54]
Need a way to accommodate either multiple HVAC systems (e.g., 70% mini-split and 30% elec baseboard) or HVAC systems that partially condition space (e.g., room AC).

**Comment by jonwinkler** [comment]
Multi-zone simulations! :-)

**Comment by nmerket** [comment]
Depends on [allowing multiple air loops in one thermal zone](https://energyplus.uservoice.com/forums/258860-energyplus/suggestions/11051238-allow-multiple-air-loops-to-one-thermal-zone). Please vote for it.

**Comment by shorowit** [comment]
Mike Witte will be working on the two EnergyPlus pieces here, targeting March E+ 8.7 release.

**Comment by joseph-robertson** [comment]
Built https://github.com/NREL/OpenStudio/tree/moreloops and working on this now.

**Comment by joseph-robertson** [comment]
Can we close or update this issue?

@shorowit

**Comment by nmerket** [comment]
I'm still doing work on EnergyPlus to add the fractions.
