### ISSUE TITLE
PV measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#61]
* [x] Where does `self.pv_system.PVDerate` in sim.py come from? That's the "System Losses" input in BEopt.

Proposal:
- [x] Include SAM SDK files (for Windows initially) in the resources dir
- [x] Supply PV characteristics, etc and perform PV run
  - [x] Determine which PV model, inverter model, etc. with appropriate inputs
- [x] Obtain PV production (at the E+ timestep?)
- [x] Determine how to inject PV production into OSM (Generator with schedule? or EMS?) ([one possible approach](https://unmethours.com/question/19744/externally-calculated-renewable-energy-as-input-to-energyplus/?answer=19982#post-id-19982))
  - [x] Since Generator:CombustionTurbine is not wrapped, will try the previous approach on the Generator:MicroTurbine object.
- [x] Success! PV output shows up in E+ output file
- [x] Add BEopt-generated annual PV values as comparison in unit tests
- [ ] Can we get the Generator:MicroTurbine to show up in the OS results?
  - [ ] See `def self.site_power_generation_table` in os_lib_reporting.rb resource file of the openstudio_results reporting measure (looks like it only includes photovoltaic and wind, and not fuel-fired).
- [ ] Need the OS team to bundle ffi

Alternative:
* ElectricLoadCenter:InverterFunctionOfPower is not wrapped. Use ElectricLoadCenterInverterSimple  or ElectricLoadCenterInverterLookUpTable instead? Can we somehow get rid of the EMS associated with the inverter?
* PhotovoltaicPerformanceSandia is not wrapped. Use PhotovoltaicPerformanceSimple  or PhotovoltaicPerformanceEquivalentOneDiode instead?

**Comment by joseph-robertson** [comment]
[ ] Where does `self.pv_system.PVDerate` in sim.py come from?

**Comment by shorowit** [comment]
That's the "System Losses" input in BEopt.

**Comment by shorowit** [comment]
E+ discussion suggests OneDiode model [has issues and needs further work](https://unmethours.com/question/20771/which-model-simulates-better-the-performance-of-photovoltaic-panels-the-sandia-or-one-diode-model/). Probably too risky to use. CEC has apparently switched to a [modified version of the PV Watts model](https://github.com/NREL/EnergyPlus/issues/5285). Suggest we either use the Simple model, if appropriate, or wrap the Sandia model. 

@craigch99 will look into the PV and Inverter questions further.

**Comment by shorowit** [comment]
We will explore using SAM for PV.

**Comment by joseph-robertson** [comment]
Started to wrap SAM's dll using ruby's ffi package. See /resources/sscapi.rb. However, can't figure out how to "pass parameters by reference" in ruby. Example of how this is done in python:
```
def data_get_number(self, p_data, name):
	val = c_number(0)
	self.pdll.ssc_data_get_number( c_void_p(p_data), c_char_p(name), byref(val) )
	return val.value
```

@shorowit @nmerket

**Comment by nmerket** [comment]
Solution: use python.

(Sorry I'm not that good at Ruby)

**Comment by shorowit** [comment]
Bottom of this page?

https://github.com/ffi/ffi/wiki/Pointers

On Feb 27, 2017, at 11:55 AM, Noel Merket <notifications@github.com<mailto:notifications@github.com>> wrote:

Solution: use python.

(Sorry I'm not that good at Ruby)

**Comment by joseph-robertson** [comment]
Aron Dobos pointed me to Rob Eger, who pointed me to https://github.nrel.gov/Technology-Deployment/ssc_api. So I think we'll be ok here.

**Comment by joseph-robertson** [comment]
For some reason I can't include the ResidentialPhotovoltaicsSAM measure in an osw file. It fails on the `require ffi` line (it finds the ffi gem, but fails to load it). However, when I run its unit tests, that same `require ffi` line executes successfully. Hmm. This interferes with the utility bill calculations measure because I cannot test having hourly pv production output available.

@shorowit
