### ISSUE TITLE
Propane/oil heating coils

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#64]
EnergyPlus only allows electricity and natural gas for HVAC heating coils. We'd like to accommodate other fuel types in E+ so as to avoid using EMS.

**Comment by ebonnema** [comment]
Related, at some point I'll need natural gas fired heat pump coils for ThermoLift (http://www.tm-lift.com/).

**Comment by jmaguire1** [comment]
Also related, I've had a few requests from Oak Ridge request gas fired heat pump water heater coils to model some of the water heaters they're developing (http://energy.gov/eere/buildings/downloads/residential-gas-fired-adsorption-heat-pump-water-heater) So far as I know this is low priority though

**Comment by shorowit** [comment]
Should be implemented, I will update our measures.
