### ISSUE TITLE
GSHP vertical bore

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#66]
Add OS measure based on BEopt model. Might need to discuss auto-sizing with NREL Commercial team.

* [x] Can we calculate the bore length multiplier? It requires first calculating `NNAGL` in sizing.rb, which is in progress.
* [x] OK to substitute CondenserLoop with PlantLoop, and then set loop type to Condenser?
* [x] FluidProperties:GlycolConcentration wrapped? How to set the fluid type to PropyleneGlycol or EthyleneGlycol with custom properties? (Kyle confirms that only Water is an option at this time.)
* [x] Adding the GFunction pairs 27 times results in 62 pairs in the osm for some reason. Solution: Needed to remove defaulted GFunction pairs first.
* [x] AirLoopHVAC:UnitaryHeatPump:WaterToAir wrapped? Can we use the unitary system object instead? I'm going with that because the prototype measure does that.
* [x] Only uses of EMS are in the `_processEMSDeliveredHeatingCoolingProgram` method
* [x] Does this equipment not get the availability schedules (heating and cooling season schedules)? Is it based on the weather / ground temps?
* [x] Add testing for valid bore field configurations
* [x] The setpoint manager follows the wrong ground temperature object (BuildingSurface instead of Deep).

**Comment by shorowit** [comment]
@joseph-robertson Could you start tackling this? I seem to recall that we thought all objects are wrapped. Since the autosizing stuff becomes complicated, I recommend only allowing fixed sizes as a way to get started. 

Please also list if there's any EMS used, so we can evaluate if we still need it.

**Comment by shorowit** [comment]
We will need the OS team to expose ReferenceGroundTemperatureObjectType so that we can use Site:GroundTemperature:Deep. It's [currently hardcoded to Site:GroundTemperature:BuildingSurface](https://github.com/NREL/OpenStudio/blob/72e4961a2d6547dcb40be48f722345b5691e3a74/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSetpointManagerFollowGroundTemperature.cpp#L60), which is not appropriate for a ground source heat pump.

We will also need the OS team to wrap the FluidProperties:GlycolConcentration object and allow Glycol as the fluid type for a PlantLoop.

cc @kbenne @nmerket

**Comment by nmerket** [comment]
This is available in OS now. Not sure what the next step is for you.

**Comment by shorowit** [comment]
Thanks! We'll wait for the next OS release and then use it in our measure.

**Comment by nmerket** [comment]
@shorowit the [fluid concentration fix](https://github.com/NREL/OpenStudio/issues/2626) should be the last of what you need to get this working. Over and out.

**Comment by shorowit** [comment]
Just remembered another open issue: https://github.com/NREL/OpenStudio/issues/2591

**Comment by shorowit** [comment]
Final testing pending.
