### ISSUE TITLE
Casting surfaces that are non-convex

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#7]
When I run the 005Chicago_2story_3000_FB_UA_Grg_NOc.osm as a seed model, I get an EnergyPlus error stating: `DetermineShadowingCombinations: There are 1 surfaces which are casting surfaces and are non-convex... Check .shd report file...`

Any idea what's going on here? .shd report file attached.
[eplusout.txt](https://github.com/NREL/OpenStudio-Beopt/files/92649/eplusout.txt)

**Comment by joseph-robertson** [comment]
@jmaguire1 to look into how important this issue is, and whether we should divide non-convex surfaces into two or more convex surfaces.

**Comment by jmaguire1** [comment]
The surface isn't completely ignored and there's still heat transfer through it, but the error could potentially be serious in terms of self shading, see: https://unmethours.com/question/1326/non-convex-surfaces-in-energyplus/

I suspect it's not a pretty minor impact on our models, but if it's not too much work to split these surfaces in half it seems like a good idea to do so.

**Comment by shorowit** [comment]
Our buildings currently won't have self-shading given that are geometry measure only creates simple boxes. I recommend not worrying about this now, hence the low priority label.

**Comment by jmaguire1** [comment]
Yeah, Joe just reminded me that the way we lay out the geometry now garages would never be in an orientation that could self shade. If and when we get to that point I can investigate further

**Comment by macumber** [comment]
You can triangulate polygons with [this method](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/geometry/Geometry.hpp#L86)

**Comment by shorowit** [comment]
This is only caused by our geometries generated by BEopt, so not an issue going forward.
