### ISSUE TITLE
Eaves interaction w/garage

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#71]
See https://github.com/NREL/OpenStudio-Beopt/issues/65. Eaves can have extra surface area when there are protruded garages. Shouldn't affect energy use but would impact eaves costing down the road.

**Comment by joseph-robertson** [comment]
![image](https://cloud.githubusercontent.com/assets/8516790/22391594/5f97672a-e4af-11e6-9664-6b687ea12591.png)

**Comment by joseph-robertson** [comment]
Need to fix:
- incorrect shading objects for 2 story, 0% protruding garage.
