### ISSUE TITLE
Eaves error

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-Beopt#74]
Not sure what's important, so here's everything.

Using EmptySeedModel.osm:
- Call SetResidentialEPWFile measure with arguments:weather_directory -> ../../../../weatherweather_file_name -> USA_OR_Pendleton-Eastern.Oregon.Rgnl.AP.726880_TMY3.epw
- Call CreateResidentialGeometry measure with arguments:total_ffa -> 2000living_height -> 8num_floors -> 2aspect_ratio -> 1.8garage_width -> 24garage_depth -> 24garage_protrusion -> 0.5garage_pos -> Rightfoundation_type -> crawl spacefoundation_height -> 4attic_type -> unfinished attic spaceroof_type -> gableroof_pitch -> 6:12
- Call AddResidentialBedroomsAndBathrooms measure with arguments:Num_Br -> 3Num_Ba -> 2occupants -> auto
- Call CreateResidentialOrientation measure with arguments:orientation -> 270
- Call CreateResidentialEaves measure with arguments:eaves_depth -> 2

Error:
user_script.rb:113:in 'get_slope_direction_and_lower_points': undefined method 'x' for nil:NilClass (NoMethodError)

**Comment by joseph-robertson** [comment]
With these geometry arguments, the garage attic height exactly equals the attic height. This results in one of the roof decks having only three vertices, causing problems downstream in the eaves measure.  I think the easiest and most efficient way to correct this is to reduce the garage attic height slightly so that it never equals the attic height.

**Comment by shorowit** [comment]
Thanks @joseph-robertson. Can you add a unit test for this situation too?

**Comment by shorowit** [comment]
Using the latest measure, I hit the same error with another geometry.

Using EmptySeedModel.osm:

- Call SetResidentialEPWFile measure with arguments:weather_directory -> ../../../../weatherweather_file_name -> USA_OR_Pendleton-Eastern.Oregon.Rgnl.AP.726880_TMY3.epw
- Call CreateResidentialGeometry measure with arguments:total_ffa -> 2000living_height -> 8num_floors -> 3aspect_ratio -> 1.8garage_width -> 24garage_depth -> 24garage_protrusion -> 0.5garage_pos -> Rightfoundation_type -> finished basement spacefoundation_height -> 8attic_type -> unfinished attic spaceroof_type -> gableroof_pitch -> 6:12
- Call AddResidentialBedroomsAndBathrooms measure with arguments:Num_Br -> 3Num_Ba -> 2occupants -> auto
- Call CreateResidentialOrientation measure with arguments:orientation -> 90
- Call CreateResidentialEaves measure with arguments:eaves_depth -> 2

Error:
user_script.rb:105:in 'get_slope_direction_and_lower_points': undefined method 'x' for nil:NilClass (NoMethodError)
