### ISSUE TITLE
Using zone multipliers in multifamily buildings

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#77]
Context: A building with 6 units could have 3 units modeled - one end unit with mult=1, another end unit with mult=1, and an interior unit with mult=4.

Investigate best approach for using zone multipliers. So far I've tried the following two approaches:
* Only drawing one interior unit. Problem: this interior unit then has surfaces adjacent to Outdoors (whereas should be adjacent to another unit), and so gets different constructions.
* Draw all the interior units, but only attach the first one to a thermal zone. Problem: OpenStudio does not translate spaces not associated with a thermal zone, and so we are left with surfaces without constructions in the IDF.

I'm thinking we take the route of the second one. However, after surface intersecting/matching and before the measure is complete, we remove all but the one interior unit associated with a thermal zone. Then loop thru all surfaces with Outside Boundary Condition "Surface" and empty Outside Boundary Condition Object. Change the Outside Boundary Condition to "Adiabatic".

**Comment by joseph-robertson** [comment]
So far results are showing that the simulations with zone multipliers have much higher energy use than the simulations without zone multipliers.

**Comment by joseph-robertson** [comment]
num_units_per_floor = 4.
![image](https://cloud.githubusercontent.com/assets/8516790/18765745/47e29ac6-80d4-11e6-8557-4353fa5e2643.png)


Not using zone multiplier approach:
![image](https://cloud.githubusercontent.com/assets/8516790/18765750/4dfc2d14-80d4-11e6-8cfa-8d3d256724fb.png)


Using zone multiplier approach:
![image](https://cloud.githubusercontent.com/assets/8516790/18765758/54868c24-80d4-11e6-91f8-de63ba3dcea5.png)

**Comment by joseph-robertson** [comment]
num_units_per_floor = 4, building_num_floors = 2, foundation_type = finished basement.
![image](https://cloud.githubusercontent.com/assets/8516790/18766240/80c7eb96-80d6-11e6-9f13-6760ea577d4b.png)

Not using zone multiplier approach:
![image](https://cloud.githubusercontent.com/assets/8516790/18766235/7a11c1fa-80d6-11e6-8dce-fcde26942a6b.png)

Using zone multiplier approach:
![image](https://cloud.githubusercontent.com/assets/8516790/18766237/7d7c2ab0-80d6-11e6-99e9-403095a986a0.png)

**Comment by shorowit** [comment]
Covered by #101.
