### ISSUE TITLE
Constructions on exterior flat roofceiling surfaces adjacent to unfinished space

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#82]
Do we have a measure to accommodate this?

This would apply to roofs of corridors.

**Comment by shorowit** [comment]
Since we're not going to deal with conditioning the corridors for the short-term, let's simply set all surfaces (walls, floors, roofs/ceilings) adjacent to the corridor zone as adiabatic. This can be done in the geometry measure.

**Comment by shorowit** [comment]
And then, the Uninsulated Surfaces measure should assign constructions to all of these surfaces. If it doesn't, we can modify the measure appropriately.

**Comment by joseph-robertson** [comment]
Good call.

**Comment by shorowit** [comment]
Yes.

**Comment by shorowit** [comment]
This seems to be implemented.
