### ISSUE TITLE
WSF in weather.rb

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#84]
Currently commented out; need to get it working.

**Comment by joseph-robertson** [comment]
I tried commenting it out and then running all of our unit tests. The measures that call weather.rb need the ASHRAE622WSF.csv file in their resources directory. I specified this in the resources.csv file, but then was hitting unit tests errors with your measures such as clothes washer. So I backed it all out, and re-commented the WSF.

**Comment by shorowit** [comment]
OK, let me see if I can figure it out.

**Comment by shorowit** [comment]
@joseph-robertson If you run into an error on Linux, please re-open this issue and post the entire error message.

**Comment by joseph-robertson** [comment]
That was quick. Haha.
