### ISSUE TITLE
Neighbor shading measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#91]
Let's add a bool argument to the Neighbors measure for whether we copy all house surfaces (as we do now) or only the minimal required surfaces (e.g., only the left-most surfaces for the right neighbor). Copying all surfaces is useful for rendering purposes (full neighbor buildings are shown) whereas minimal copying is useful for the actual simulations (much faster runtime, particularly for MF buildings). Default to the minimal version.

**Comment by shorowit** [comment]
Something isn't right here...

![neighbors](https://cloud.githubusercontent.com/assets/5861765/18324345/3dc018d4-74f9-11e6-9a43-8d3187852c5a.png)

**Comment by joseph-robertson** [comment]
47d501d

**Comment by shorowit** [comment]
Can we also accommodate the appropriate hip roof surface?

![hiproof](https://cloud.githubusercontent.com/assets/5861765/18326686/44e6514a-7504-11e6-8f0e-4e6bf8c4bef3.png)

**Comment by shorowit** [comment]
Another example:

![neighbors_fb](https://cloud.githubusercontent.com/assets/5861765/18326887/1cb90f2c-7505-11e6-9e31-f5b3729bdd01.png)

**Comment by shorowit** [comment]
Let's modify the algorithm so that we retain all wall/roof surfaces that face a given direction (e.g., left facade walls/roofs for the right neighbor).

**Comment by shorowit** [comment]
I will test.

**Comment by shorowit** [comment]
This seems to be working well. I'm going to keep the ticket open as low priority because it would be nice if we could exclude neighbor shading surfaces that are directly behind other shading surfaces, which occurs when using the Neighbors measure on a MF building. But that's just an E+ speed optimization thing.

**Comment by shorowit** [comment]
Unfortunately, I found situations where this doesn't work well and it's not obvious how to improve the algorithm. I'm going to remove the "Copy all surfaces" argument.
