### ISSUE TITLE
Require finished basements to be attached to above-grade units?

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#93]
Does a finished basement have to be attached to an above-grade unit, or can it be its own unit?

Need to answer this for, e.g., airflow measure because Geoemtry.get_above_grade_finished_floor_area_from_spaces() returns zero if the answer is no.

**Comment by shorowit** [comment]
We didn't allow it in BEopt. I'm not sure I remember all of the reasons offhand... 

cc @ejhw @craigch99

On a related note, I wonder whether we should change the "Num Stories Per Unit" input in the MF geometry measure to something like "Unit Spans All Stories?" (can't think of a great name), which would mean that the unit spans all stories of the building, including finished basement if present. We also then wouldn't have to deal with multi-story units stacked on top of multi-story units, which is likely not realistic.

**Comment by ejhw** [comment]
I think we would like to allow finished basements be their own units (e.g. garden-level apartments) eventually, but it's not a high priority. I think the reasons it isn't allowed currently include questions about appropriate infiltration, MELs/appliance locations, windows/doors, etc.

**Comment by joseph-robertson** [comment]
Decision is to only allow finished basements in single-family attached buildings (finished basement space + above-grade living space is one unit). This way, all single-family building units' floor area is preserved as equal.
