### ISSUE TITLE
Supply fan operation outside heating/cooling seasons

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#96]
In BEopt, we use the `ThermostatSetpoint:SingleCooling` and `ThermostatSetpoint:SingleHeating` objects. But because OpenStudio only has the `ThermostatSetpointDualSetpoint` object wrapped, we use extremely low heating setpoints and high cooling setpoints for situations where there is no heating/cooling equipment to prevent fan operation. See https://github.com/NREL/OpenStudio-BEopt/issues/19#issuecomment-229182839 for context. If we wrapped these two thermostat objects in OpenStudio, we could remove this workaround.

However, there is also the issue where the supply fan can run outside the heating/cooling seasons. In BEopt, we solved this by using a SupplyFanScheduleProgram EMS program. However, we'd really like to avoid EMS in OpenStudio if we can. Instead, we could use a similar solution to above by using extremely low heating setpoints outside the heating season and high cooling setpoints outside the cooling season.

Any reason this wouldn't work?

cc @ejhw @jmaguire1 @jonwinkler

**Comment by shorowit** [comment]
Sorry, copy-pasted the wrong object names the first time. Now fixed above.

**Comment by jmaguire1** [comment]
I think this would work just fine. In fact, I thought we were already doing it (or had done it previously). It's definitely what I thought the original issue was in #19. I can't think of how this might be a problem for any of the HVAC equipment (ceiling fans I think we might still need to have some EMS related to heating/cooling seasons, but that should be it's own issue).

**Comment by ejhw** [comment]
Sounds like it would work to me.

**Comment by jmaguire1** [comment]
Just talked to Joe about this and it looks like we're already doing this.  If there's heating/cooling equipment in the home, we're already setting the setpoint very low/high (respectively) for months that are outside of the heating/cooling season. Joe and I forgot to mention that part in the previous ticket, but it has been implemented for a while in the changes in #19. Unless you're seeing a specific case where this isn't happening I think this is already done.
