### ISSUE TITLE
Duplicate HVAC-related objects

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BEopt#97]
Create a building with a furnace and air conditioner. There will be duplicate objects in the osm/idf, including:
- SupplyFanAvailability Schedule
- SupplyFanOperation Schedule
- Fan On Off Power Curve
- Fan On Off Efficiency Curve

**Comment by joseph-robertson** [comment]
@shorowit I create new objects for each building unit's piece of equipment. What do you suppose our approach should be? First search the osm for objects whose name starts with some string?

**Comment by shorowit** [comment]
I'm not really sure what you're asking. 

Apparently in the process of adding a furnace and AC, you end up creating, e.g., two SupplyFanAvailability Schedules, but only one ends up referenced by another object in the model. Isn't it simply a matter of, when assigning the second schedule to the object that references, delete the existing schedule? Or don't create/assign a new schedule if one has already been assigned?

**Comment by joseph-robertson** [comment]
You're right, I thought you were talking about something else. I'll try to make the fix.

**Comment by joseph-robertson** [comment]
So I'm able to remove the duplicate SupplyFanAvailability and SupplyFanOperation schedules, but not the Fan On Off Curves, for some reason. See def self.has_furnace() in hvac.rb..

**Comment by joseph-robertson** [comment]
Following up on Curves. Talked further with Kyle about not being able to remove Curves. He said these, along with other "resource objects", can live on their own in the model and calling remove on them will only work after all of the things using them are first removed. I verified this works for, e.g., day schedule objects. But it still won't work for Curves. Hmm.

**Comment by shorowit** [comment]
This is probably good enough.
