### ISSUE TITLE
Differences in OS/E+ input default values (VRF MSHP)

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#99]
Possible discrepancies between modeling in BEopt/E+ and OpenStudio/E+ because of defaulted values:

* AirConditionerVariableRefrigerantFlow
 - setEquivalentPipingLengthusedforPipingCorrectionFactorinCoolingMode
   - BEopt: 0, OS: 30 
  **Need to overwrite OS default value**
 - setVerticalHeightusedforPipingCorrectionFactor
   - BEopt: 0, OS: 10
   **Need to overwrite OS default value**
 - setPipingCorrectionFactorforHeightinCoolingModeCoefficient
   - BEopt: 0, OS: -0.000386
   **Need to overwrite OS default value**
 - setEquivalentPipingLengthusedforPipingCorrectionFactorinHeatingMode
   - BEopt: 0, OS: 30
   **Need to overwrite OS default value**
 - setDefrostTimePeriodFraction
   - BEopt: 0, OS: 0.058333
   **No change required**
 - setEvaporativeCondenserEffectiveness
   - BEopt: 0, OS: 0.9
   **No change required (BEopt is actually defaulting to 0.9)**
 - setBasinHeaterSetpointTemperature
   - BEopt: 0, OS: 2
   **No change required**
 - setMaximumOutdoorTemperatureinHeatRecoveryMode
   - BEopt: 0, OS: 20
   **No change required**
 - setInitialHeatRecoveryCoolingCapacityFraction 
    - BEopt: 0, OS: 0.5
   **No change required**
 - setInitialHeatRecoveryCoolingEnergyFraction
   - BEopt: 0, OS: 1
   **No change required**
 - setInitialHeatRecoveryHeatingCapacityFraction
   - BEopt: 0, OS: 0.5
   **No change required**
 - setInitialHeatRecoveryHeatingEnergyFraction
   - BEopt: 0, OS: 0.5
   **No change required**
 - setHeatRecoveryCoolingCapacityTimeConstant
   - BEopt: 0, OS: 0.083
   **No change required**
 - setHeatRecoveryHeatingCapacityTimeConstant
   - BEopt: 0, OS: 0.083
   **No change required**

* ZoneHVACTerminalUnitVariableRefrigerantFlow
 - Supply Air Fan Placement
    BEopt: "BlowThrough", OS: "DrawThrough" (this does not appear to be wrapped)

**Comment by jmaguire1** [comment]
I've marked up the list with what I think we need to be concerned about. I think we only really need to make sure that we're not using any of the piping correction factors since we haven't tested that feature out. Otherwise, the defaults are largely related to things we're not using.

**Comment by joseph-robertson** [comment]
@jmaguire1 How large of a difference might using "DrawThrough" instead of "BlowThrough" for the terminal unit's supply air fan placement cause?

**Comment by jmaguire1** [comment]
It should be pretty small, "DrawThrough" has the fan after the coil (so heat it generates doesn't impact coil heat transfer), while "BlowThrough" has the fan before the coil. I'd be very surprised if it changed the results by more than a few %

**Comment by joseph-robertson** [comment]
Remaining issues captured in #98.
